extends Node
## The S4 rule-engine suite (`make godot-rules`): invariant **I5** and the
## ECHOES §5 semantics, driven deterministically.
##
## Boots the real project (`--rules-test`) because the runtime reads the
## BridgeClient autoload; needs no bridge. The snapshot in
## `fixtures/rules_snapshot.json` is a REAL fold on the Python side — two
## resources, nineteen rules, and a MERGE whose alias a rule cost still
## references — regenerated by `make_rules_fixture.py` (scratch tooling;
## the fold, not this file, owns the shape).
##
## Everything is ticked by hand at 1/60 with the pool off-tree: I5 is a
## statement about ticks, and wall-clock frames would make it flaky.

const DT := 1.0 / 60.0

var failures := 0

func _check(condition: bool, message: String) -> void:
	if not condition:
		failures += 1
		push_error("FAIL: " + message)
		print("FAIL: " + message)

class StubPlayer:
	extends RefCounted
	var hp := 100.0
	var max_hp := 100.0
	var velocity := Vector3.ZERO
	var global_transform := Transform3D.IDENTITY
	var global_position := Vector3.ZERO
	var grounded := true
	func is_on_floor() -> bool:
		return grounded
	func heal(amount: float) -> void:
		hp = minf(max_hp, hp + amount)

var _pool: ResourcePool
var _runtime: RuleRuntime
var _player: StubPlayer
var _fired: Dictionary = {}

func _ready() -> void:
	var raw := FileAccess.get_file_as_string(
			"res://tests/fixtures/rules_snapshot.json")
	var snapshot: Variant = JSON.parse_string(raw)
	_check(typeof(snapshot) == TYPE_DICTIONARY, "the fixture parses")
	BridgeClient.snapshot = snapshot

	_edge_is_deferred_and_edge_only()
	_oscillation_is_cooldown_bounded()
	_the_cap_skips_rather_than_queues()
	_costs_are_all_or_nothing()
	_conditions_all_hold()
	_cooldown_holds_a_rule_down()
	_aliases_resolve_for_costs()
	_low_health_is_an_edge()
	_a_refused_payment_leaves_regen_alone()
	_a_negative_resource_add_arms_the_delay()
	_an_arm_belongs_to_the_value_that_made_it()
	_zone_entry_resets_the_latches_and_the_cooldowns()

	if _runtime != null:
		_runtime.free()
	if _pool != null:
		_pool.free()
	if failures == 0:
		print("GODOT RULES TESTS OK")
		get_tree().quit(0)
	else:
		print("GODOT RULES TESTS: %d failures" % failures)
		get_tree().quit(1)

## Fresh pool + runtime, watched values seeded by one quiet tick.
func _fresh(with_player := false) -> void:
	if _runtime != null:
		_runtime.free()
	if _pool != null:
		_pool.free()
	_pool = ResourcePool.new()
	_pool.reset_for_zone()
	_runtime = RuleRuntime.new()
	_runtime.pool = _pool
	_player = StubPlayer.new() if with_player else null
	_runtime.player = _player
	_runtime.refresh_rules()
	_fired.clear()
	_runtime.rule_fired.connect(func(rule_id: String) -> void:
		_fired[rule_id] = int(_fired.get(rule_id, 0)) + 1)
	_runtime.tick(DT)

func _drive(frames: int) -> void:
	for i in frames:
		_runtime.tick(DT)

func _effects_of(rule_id: String) -> int:
	var count := 0
	for entry: Dictionary in _runtime.effect_log:
		if str(entry.get("rule_id", "")) == rule_id:
			count += 1
	return count

# --- I5: an effect that fills does not dispatch resource_full this tick --

func _edge_is_deferred_and_edge_only() -> void:
	_fresh()
	# Park the oscillator's resource mid-bar first. Events are BARE kinds:
	# the battery's crossing arms every `resource_full` listener, and the
	# drain rule's own condition then reads a full osc — leave osc full and
	# this scenario starts the oscillator instead of isolating one edge.
	_pool.spend("res_osc", _pool.value_of("res_osc") * 0.5)
	_runtime.notify("check_claimed")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_charge", 0)) == 1, "the filler fired")
	_check(_pool.is_full("res_battery"), "the battery filled")
	_check(int(_fired.get("rule_on_full", 0)) == 0,
			"resource_full did NOT dispatch in the tick that filled it")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_on_full", 0)) == 1,
			"resource_full dispatched on the next tick, once")
	_drive(30)
	_check(int(_fired.get("rule_on_full", 0)) == 1,
			"a value SITTING at full fires nothing — edge, not level")

# --- I5: fill-on-empty / drain-on-full oscillates at the cooldown rate ---

func _oscillation_is_cooldown_bounded() -> void:
	_fresh()
	_pool.spend("res_osc", _pool.value_of("res_osc"))
	_drive(120)  # two seconds
	var fills := int(_fired.get("rule_fill_on_empty", 0))
	var drains := int(_fired.get("rule_drain_on_full", 0))
	_check(fills >= 8, "the oscillator sustains — the edge latch survives "
			+ "the cooldown (%d fills)" % fills)
	# The pair interleaves, so each rule fires once per ITS 0.1 s cooldown:
	# at most 20 each in 2 s, against ~120 for the unbounded every-tick
	# runaway this cap exists to rule out.
	_check(fills <= 21 and drains <= 21,
			"oscillation is cooldown-bounded (%d fills, %d drains in 2 s)"
			% [fills, drains])

# --- I5: the per-tick cap skips, and skipped rules do not queue ----------

func _the_cap_skips_rather_than_queues() -> void:
	_fresh()
	_runtime.notify("kill")
	_runtime.tick(DT)
	var fired_now := 0
	for i in 10:
		fired_now += int(_fired.get("rule_cap_%02d" % i, 0))
	_check(fired_now == Constants.RULE_FIRINGS_PER_TICK_CAP,
			"one tick fires at most the cap (%d fired)" % fired_now)
	_drive(30)
	var fired_later := 0
	for i in 10:
		fired_later += int(_fired.get("rule_cap_%02d" % i, 0))
	_check(fired_later == fired_now,
			"rules the cap skipped were skipped, not queued")

# --- Costs: unaffordable means the rule does not fire, and pays nothing --

func _costs_are_all_or_nothing() -> void:
	_fresh()
	var start := _pool.value_of("res_battery")
	_pool.spend("res_battery", start - 20.0)
	_runtime.notify("land")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_landing_tax", 0)) == 0,
			"an unaffordable rule does not fire")
	_check(is_equal_approx(_pool.value_of("res_battery"), 20.0),
			"...and takes nothing")
	_pool.refill("res_battery", 40.0)
	_runtime.notify("land")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_landing_tax", 0)) == 1,
			"an affordable rule fires")
	_check(is_equal_approx(_pool.value_of("res_battery"), 30.0),
			"...and pays exactly its cost")
	# Two costs, second unaffordable: the first must be REFUNDED. This is
	# the atomicity §5's "unaffordable ⇒ the rule does not fire" implies —
	# firing poorer with nothing to show is the outcome it bans. Osc is
	# parked mid-bar throughout: touch either of its thresholds and the
	# oscillator pair wakes up inside this scenario.
	_pool.spend("res_osc", _pool.value_of("res_osc") - 10.0)
	var battery := _pool.value_of("res_battery")
	_runtime.notify("chamber_enter")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_double_cost", 0)) == 0,
			"a rule that can pay only its first cost does not fire")
	_check(is_equal_approx(_pool.value_of("res_battery"), battery),
			"...and the first cost was refunded")
	_pool.refill("res_osc", 20.0)
	_drive(8)  # clear the cooldown charged by nothing — none was: fresh try
	_runtime.notify("chamber_enter")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_double_cost", 0)) == 1,
			"both costs affordable, the rule fires")
	_check(is_equal_approx(_pool.value_of("res_osc"), 15.0),
			"...paying the second cost too")

# --- Conditions: all must hold -------------------------------------------

func _conditions_all_hold() -> void:
	_fresh(true)
	_player.grounded = false
	_runtime.notify("dash_end")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_dash_reward", 0)) == 0,
			"one failing condition blocks the rule")
	_player.grounded = true
	_runtime.notify("dash_end")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_dash_reward", 0)) == 1,
			"all conditions holding lets it fire")
	_check(_effects_of("rule_dash_reward") == 1
			and str(_runtime.effect_log[-1]["effect"].get("type", ""))
			== "impulse_self",
			"the effect reached the log")

# --- Cooldown: schema-floored, and enforced ------------------------------

func _cooldown_holds_a_rule_down() -> void:
	_fresh()
	_runtime.notify("jump")
	_runtime.tick(DT)
	_runtime.notify("jump")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_slow_jump", 0)) == 1,
			"a second event inside the cooldown does not fire")
	_drive(32)  # past the 0.5 s cooldown
	_runtime.notify("jump")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_slow_jump", 0)) == 2,
			"the cooldown expiring frees the rule")

# --- Aliases: a cost against an absorbed id spends the survivor ----------

func _aliases_resolve_for_costs() -> void:
	_fresh()
	var before := _pool.value_of("res_battery")
	_runtime.notify("parry_success")
	_runtime.tick(DT)
	_check(int(_fired.get("rule_old_cost", 0)) == 1,
			"a rule written against an absorbed resource still fires")
	_check(is_equal_approx(_pool.value_of("res_battery"), before - 10.0),
			"...and its cost lands on the survivor")

# --- low_health is an edge on the shared threshold -----------------------

func _low_health_is_an_edge() -> void:
	_fresh(true)
	_drive(5)
	_player.hp = 20.0
	_drive(2)
	_check(int(_fired.get("rule_low", 0)) == 1,
			"dropping under the threshold derives low_health once")
	_drive(30)
	_check(int(_fired.get("rule_low", 0)) == 1,
			"staying low re-fires nothing — edge, not level")
	_player.hp = 80.0
	_drive(2)
	_player.hp = 10.0
	_drive(2)
	_check(int(_fired.get("rule_low", 0)) == 2,
			"recovering and crossing again re-derives it")
	_check(_effects_of("rule_low") == 2
			and str(_runtime.effect_log[-1]["effect"].get("type", ""))
			== "grant_shield",
			"the shield effect reached the log both times")

## A rule that can pay its first cost but not its second must leave the
## channel exactly as it found it -- the VALUE and the regen delay.
##
## The old refund path put the value back with `refill` and left the
## `regen_delay` the `spend` had armed. That is invisible until a channel
## actually regenerates, and none in the old fixture did. It is not a
## rounding error: an armed edge event dispatches every physics frame, so
## the delay was re-armed sixty times a second and regeneration stopped
## dead -- on a rule that never fired once.
func _a_refused_payment_leaves_regen_alone() -> void:
	_fresh()
	# res_bat2 regenerates 25/s after a 5 s delay. rule_greedy costs 1 of
	# it and 200 of res_osc, which holds 40 at most.
	_pool.spend("res_bat2", 80.0)
	var start := _pool.value_of("res_bat2")
	_check(is_equal_approx(start, 20.0), "the channel starts drained")
	# Let the delay from that setup spend itself before measuring.
	for i in range(int(11.0 / DT)):
		_pool._process(DT)
	var recovered := _pool.value_of("res_bat2")
	_check(recovered > 90.0, "a channel left alone regenerates: %f" % recovered)

	# Now the same window, with the greedy rule retrying every frame.
	_pool.spend("res_bat2", _pool.value_of("res_bat2") - 20.0)
	for i in range(int(11.0 / DT)):
		_pool._process(DT)
		_runtime.notify("chamber_enter")
		_runtime.tick(DT)
	_check(int(_fired.get("rule_greedy", 0)) == 0,
			"the greedy rule never fires")
	var after := _pool.value_of("res_bat2")
	_check(after > 90.0,
			"...and regeneration is untouched by its attempts: %f" % after)

## `Effect.amount` allows a negative, and a negative `resource_add` is a
## drain. It used to go through `refill`, the one door that does not arm
## `regen_delay` -- so the delay was decorative for exactly the effect
## most likely to be spammed.
func _a_negative_resource_add_arms_the_delay() -> void:
	_fresh()
	var before := _pool.value_of("res_bat2")
	_runtime._apply_effect("rule_test", {
		"type": "resource_add", "subject": "res_bat2", "amount": -50.0})
	_check(is_equal_approx(_pool.value_of("res_bat2"), before - 50.0),
			"the drain takes what it asked for")
	# One second of regen must NOT arrive: the delay is 5 s.
	for i in range(int(1.0 / DT)):
		_pool._process(DT)
	_check(is_equal_approx(_pool.value_of("res_bat2"), before - 50.0),
			"...and the regen delay is armed, as a spend would have armed it")
	# A drain takes what is there rather than refusing: it is damage to the
	# bar, not a transaction the player is paying.
	_runtime._apply_effect("rule_test", {
		"type": "resource_add", "subject": "res_bat2", "amount": -500.0})
	_check(is_equal_approx(_pool.value_of("res_bat2"), 0.0),
			"an oversized drain empties rather than refusing")

## "A value that left its threshold takes unfired arms with it" -- which
## it did not. `crossed` and `holding` were computed per EVENT KIND across
## every resource, so `holding["resource_full"]` was true if ANY owned
## resource was full. A latch armed by one bar crossing full was kept
## alive by a second, unrelated bar that happened to be full, and the rule
## fired seconds later against a threshold that had long since ended.
func _an_arm_belongs_to_the_value_that_made_it() -> void:
	_fresh(true)
	# res_battery is the bystander: filled and held there for the whole
	# scenario. res_osc is parked mid-bar so the oscillator pair stays
	# asleep, and res_bat2 is parked below full so it can cross.
	_pool.refill("res_battery", 200.0)
	_pool.spend("res_osc", _pool.value_of("res_osc") * 0.5)
	_pool.spend("res_bat2", 50.0)
	# Reset rather than tick it out: this is the state the scenario starts
	# FROM, so none of it should read as an edge.
	_runtime.reset_for_zone()
	_player.hp = 100.0
	_runtime.tick(DT)
	_check(_pool.is_full("res_battery"), "the bystander is full throughout")
	_check(not _runtime._armed.has("rule_full_when_hurt"),
			"nothing is armed to begin with")

	# res_bat2 crosses full: the latch arms, and cannot fire, because the
	# player is healthy.
	_pool.refill("res_bat2", 100.0)
	_runtime.tick(DT)
	_check(_runtime._armed.has("rule_full_when_hurt"),
			"crossing full arms the rule")
	_check(int(_fired.get("rule_full_when_hurt", 0)) == 0,
			"...without firing, because the condition does not hold")

	# res_bat2 leaves full -- halfway down, not to empty: emptying it
	# would fire `rule_fill_on_empty`, which tops up res_osc and wakes the
	# oscillator pair inside this scenario. Its edge is over either way,
	# and res_battery is still full, which used to keep this latch alive
	# on its behalf.
	_pool.spend("res_bat2", _pool.value_of("res_bat2") * 0.5)
	_runtime.tick(DT)
	_check(not _runtime._armed.has("rule_full_when_hurt"),
			"a latch dies with the value that armed it, not with the kind")

	# The proof that it mattered: the condition becoming true long after
	# the edge ended must NOT fire the rule.
	_player.hp = 10.0
	for i in range(int(1.0 / DT)):
		_runtime.tick(DT)
	_check(int(_fired.get("rule_full_when_hurt", 0)) == 0,
			"...so it cannot fire a second after its edge ended (%d)"
			% int(_fired.get("rule_full_when_hurt", 0)))

	# And a real edge, with the condition holding, still fires it.
	_pool.refill("res_bat2", 100.0)
	_runtime.tick(DT)
	_runtime.tick(DT)
	_check(int(_fired.get("rule_full_when_hurt", 0)) == 1,
			"a real edge still fires the rule watching that kind (%d)"
			% int(_fired.get("rule_full_when_hurt", 0)))

## I9 resets resource values and statuses on Zone entry. Every latch,
## cooldown and watched value in here is DERIVED from exactly that state,
## and none of them was cleared -- so a latch armed in one Zone fired on
## the first tick of the next, and a cooldown charged in one Zone held a
## rule down in another.
func _zone_entry_resets_the_latches_and_the_cooldowns() -> void:
	_fresh()
	_pool.spend("res_osc", _pool.value_of("res_osc"))
	_runtime.tick(DT)
	_pool.refill("res_osc", 100.0)
	_runtime.tick(DT)
	_runtime.notify("land")
	_runtime.tick(DT)
	_check(not _runtime._armed.is_empty() or not _runtime._cooldowns.is_empty(),
			"the first Zone leaves state behind")

	_pool.reset_for_zone()
	_runtime.reset_for_zone()
	_check(_runtime._armed.is_empty(), "Zone entry clears the latches")
	_check(_runtime._cooldowns.is_empty(), "...and the cooldowns")
	_check(_runtime._watched_fractions.is_empty(),
			"...and the watched values, which would otherwise read the new "
			+ "Zone's fresh fractions as an edge against the old Zone's")
	_fired.clear()
	_runtime.tick(DT)
	_check(_fired.is_empty(),
			"...so the new Zone's first tick fires nothing: %s" % [_fired])
