extends Node
## The S2/S5 action-runner suite (`make godot-verbs`): the press and
## release lifecycle, and the four holes an adversarial pass found in it.
##
## Boots the real project (`--verbs-test`) with a real `Player`, a real
## `ResourcePool` and the four real `EchoRuntime` nodes, over a flat floor
## with real physics frames. The snapshot in `fixtures/verbs_snapshot.json`
## is a REAL fold, regenerated by `make verbs-fixture`.
##
## Every verb here carries a five-second cooldown, because every question
## in this file is some form of "was this press charged for?" and five
## seconds makes the answer unambiguous.
##
## What it holds:
##   1. `release()` resolves only a press that actually resolved
##   2. a refused press gives back the cost, the cooldown and the fill
##   3. death ends every hold, in every slot
##   4. a slot swap ends a hover -- an I3 bypass if it does not
##   5. one slot's key-up does not end another slot's hover

const DT := 1.0 / 60.0

var failures := 0
var _player: Player = null
var _pool: ResourcePool = null
var _floor: StaticBody3D = null
var _uses := 0

func _count_use() -> void:
	_uses += 1

var _parries := 0

func _count_parry() -> void:
	_parries += 1

func _check(condition: bool, message: String) -> void:
	if not condition:
		failures += 1
		push_error("FAIL: " + message)
		print("FAIL: " + message)

func _ready() -> void:
	_run()

func _run() -> void:
	var raw := FileAccess.get_file_as_string(
			"res://tests/fixtures/verbs_snapshot.json")
	var snapshot: Variant = JSON.parse_string(raw)
	_check(typeof(snapshot) == TYPE_DICTIONARY, "the fixture parses")
	BridgeClient.snapshot = snapshot

	await _build_world()

	await _a_release_without_a_press_does_nothing()
	await _a_refused_press_gives_everything_back()
	await _death_ends_every_hold()
	await _a_slot_swap_ends_a_hover()
	await _one_slots_key_up_leaves_another_slots_hover_alone()
	await _two_hovers_at_once_do_not_cancel_each_other()
	await _a_burn_tick_does_not_spend_the_parry_window()
	await _an_absorbed_shield_does_not_inflate_the_next_one()
	await _rule_effects_follow_the_slot_the_player_is_looking_at()

	if failures == 0:
		print("GODOT VERBS TESTS OK")
		get_tree().quit(0)
	else:
		print("GODOT VERBS TESTS: %d failures" % failures)
		get_tree().quit(1)

func _build_world() -> void:
	_floor = StaticBody3D.new()
	var shape := CollisionShape3D.new()
	var box := BoxShape3D.new()
	box.size = Vector3(60, 1, 60)
	shape.shape = box
	shape.position = Vector3(0, -0.5, 0)
	_floor.add_child(shape)
	add_child(_floor)

	_pool = ResourcePool.new()
	_pool.name = "ResourcePool"
	add_child(_pool)

	_player = Player.create()
	add_child(_player)
	_player.global_position = Vector3(0, 1, 0)
	# Frozen input: this suite drives `activate()` and `release()` by hand,
	# because the questions are about what those two do, not about which
	# key produced them.
	_player.input_frozen = true
	for slot: String in Constants.SLOT_NAMES:
		var runtime: EchoRuntime = _player.runtimes[slot]
		runtime.pool = _pool
		var equipped: Variant = BridgeClient.slots().get(slot)
		if equipped != null:
			runtime.set_equipped(
					BridgeClient.owned_component(str(equipped)).get(
							"component", {}))
	_player.stat_stack.pool = _pool
	await get_tree().physics_frame
	await get_tree().physics_frame

func _reset() -> void:
	_pool.reset_for_zone()
	for slot: String in Constants.SLOT_NAMES:
		var runtime: EchoRuntime = _player.runtimes[slot]
		runtime.cancel_holds()
		runtime.reset_cooldown()
		runtime.shield_hp = 0.0
		runtime._shield_timer = 0.0
		runtime._parry_window = 0.0
		# Re-equipped every time: `_a_slot_swap_ends_a_hover` hands the
		# mobility runtime a different Action, and that is the point of it.
		var equipped: Variant = BridgeClient.slots().get(slot)
		if equipped != null:
			runtime.set_equipped(
					BridgeClient.owned_component(str(equipped)).get(
							"component", {}))
	_player.hover_gravity_scale = 1.0
	if _player._dead:
		_player._respawn()
	await get_tree().physics_frame

func _runtime(slot: String) -> EchoRuntime:
	return _player.runtimes[slot]

# --- 1: release with no press --------------------------------------------

## `player.gd` calls `release()` on every key-up, whether or not the
## matching `activate()` got past the cooldown, the conditions, the gates
## and the cost. Matching on the primitive alone meant `charge_shot` fired
## from a key-up with no press behind it: no cooldown charged, no gate
## checked, no cost paid, one bolt per tap.
func _a_release_without_a_press_does_nothing() -> void:
	await _reset()
	var runtime := _runtime("echo_b")

	# A real press, so the cooldown is genuinely running.
	runtime.activate()
	await get_tree().physics_frame
	runtime.release()
	_check(runtime.cooldown_remaining > 4.0,
			"a real press charges the cooldown: %f"
			% runtime.cooldown_remaining)

	var spark_before := _pool.value_of("res_spark")
	var bolts_before := _count_projectiles()
	# Now tap the key while it cools. Every one of these presses is
	# refused by the cooldown check, so no release may resolve.
	for i in range(6):
		runtime.activate()
		runtime.release()
		await get_tree().physics_frame
	_check(_count_projectiles() == bolts_before,
			"no bolt escapes from a key-up with no press behind it (%d new)"
			% (_count_projectiles() - bolts_before))
	_check(is_equal_approx(_pool.value_of("res_spark"), spark_before),
			"...and nothing was spent for them")

## Projectiles are parented to the current scene and belong to no group,
## so they are counted by walking it.
func _count_projectiles() -> int:
	var n := 0
	for node: Node in get_tree().current_scene.get_children():
		if node is EchoProjectile:
			n += 1
	return n

# --- 2: the refund is complete -------------------------------------------

## A blink with nowhere to land refunds its press. It used to refund only
## the cooldown -- the smallest of the three things a press costs. The
## `powers` cost stayed spent and `_apply_fills` ran anyway, so a refused
## press was net GENERATION with the cooldown handed back: aim at the sky,
## hold the key, print resource without bound.
func _a_refused_press_gives_everything_back() -> void:
	await _reset()
	var runtime := _runtime("echo_a")
	# Straight up, at a ceiling that is not there: the blink sweep finds no
	# surface, so the press cannot resolve.
	_player.global_position = Vector3(0, 1, 0)
	_player.camera.global_rotation = Vector3(PI / 2.0, 0, 0)
	await get_tree().physics_frame

	var fuel := _pool.value_of("res_fuel")
	# Drained first, or the fill clamps at full and the most alarming half
	# of this -- a refused press PRINTING resource -- measures nothing.
	_pool.spend("res_spark", 60.0)
	var spark := _pool.value_of("res_spark")
	_uses = 0
	if not runtime.action_used.is_connected(_count_use):
		runtime.action_used.connect(_count_use)

	for i in range(4):
		runtime.activate()
		await get_tree().physics_frame

	_check(is_equal_approx(_pool.value_of("res_fuel"), fuel),
			"a refused press keeps no cost: %f of %f"
			% [_pool.value_of("res_fuel"), fuel])
	_check(is_equal_approx(_pool.value_of("res_spark"), spark),
			"...pays no fill: %f of %f"
			% [_pool.value_of("res_spark"), spark])
	_check(_uses == 0,
			"...and emits no action_used, which means 'a press that "
			+ "genuinely resolved' (%d)" % _uses)
	_check(is_equal_approx(runtime.cooldown_remaining, 0.0),
			"...while the cooldown is still given back")

	# And the ordinary case still works, or the guard became a wall.
	_player.camera.global_rotation = Vector3(-PI / 6.0, 0, 0)
	await get_tree().physics_frame
	runtime.activate()
	await get_tree().physics_frame
	_check(_pool.value_of("res_fuel") < fuel,
			"a blink that lands still pays its cost")
	_check(_uses == 1, "...and still reports itself used (%d)" % _uses)

# --- 3: death ends every hold --------------------------------------------

## `Player._physics_process` returns at `_dead`, so `release()` is never
## polled and `set_grounded()` is never called -- but each `EchoRuntime`
## is a separate node with its own `_physics_process`, and they kept
## running. A beam went on damaging and draining, a burst went on firing,
## and `_held` survived the respawn because the key-up edge was consumed
## by the input branch a dead player skips.
func _death_ends_every_hold() -> void:
	await _reset()
	var beam := _runtime("utility")
	var hover := _runtime("mobility")
	beam.activate()
	hover.activate()
	await get_tree().physics_frame
	_check(beam._held, "the beam is held before the death")
	_check(hover._held, "the hover is held before the death")

	_player.take_damage(10000.0)
	await get_tree().physics_frame
	_check(_player._dead, "the player is dead")
	_check(not beam._held, "death ends the beam's hold")
	_check(not hover._held, "death ends the hover's hold")

	var fuel := _pool.value_of("res_fuel")
	for i in range(20):
		await get_tree().physics_frame
	_check(is_equal_approx(_pool.value_of("res_fuel"), fuel),
			"...and nothing drains from a corpse: %f of %f"
			% [_pool.value_of("res_fuel"), fuel])
	_check(is_equal_approx(_player.hover_gravity_scale, 1.0),
			"...and the hover's gravity scale is released")

# --- 4 and 5: the hover, which writes shared player state -----------------

## `player.gravity_mult` is floored by `clamp_stat`, but
## `hover_gravity_scale` is multiplied in AFTERWARDS and the stat stack
## never sees it. A hover left running by a slot swap is therefore an I3
## bypass, and `Hover.gravity_multiplier` goes down to 0.0 -- permanent
## zero gravity, from swapping slots at the wrong moment.
func _a_slot_swap_ends_a_hover() -> void:
	await _reset()
	var hover := _runtime("mobility")
	hover.activate()
	await get_tree().physics_frame
	_check(_player.hover_gravity_scale < 1.0,
			"the hover lightens gravity: %f" % _player.hover_gravity_scale)

	# The same runtime is handed a different Action, which is what a slot
	# swap does.
	hover.set_equipped(BridgeClient.owned_component("act_blink").get(
			"component", {}))
	for i in range(10):
		await get_tree().physics_frame
	_check(is_equal_approx(_player.hover_gravity_scale, 1.0),
			"a slot swap ends the hover rather than stranding it: %f"
			% _player.hover_gravity_scale)

## `_end_hover` wrote `player.hover_gravity_scale = 1.0` unconditionally,
## and `hover_gravity_scale` is shared between the four slots. So a key-up
## from a slot that never hovered cancelled the hover of a slot that had --
## which kept `_held`, kept paying its per-frame drain, and lifted nothing.
func _one_slots_key_up_leaves_another_slots_hover_alone() -> void:
	await _reset()
	var hover := _runtime("mobility")
	var beam := _runtime("utility")
	hover.activate()
	await get_tree().physics_frame
	var lightened := _player.hover_gravity_scale
	_check(lightened < 1.0, "the hover is lifting")

	# The beam's key comes up without its key ever having gone down.
	beam.release()
	await get_tree().physics_frame
	_check(is_equal_approx(_player.hover_gravity_scale, lightened),
			"another slot's key-up leaves the hover lifting: %f of %f"
			% [_player.hover_gravity_scale, lightened])
	_check(hover._held, "...and the hovering slot is still held")

	# The hover's own key-up still ends it.
	hover.release()
	await get_tree().physics_frame
	_check(is_equal_approx(_player.hover_gravity_scale, 1.0),
			"its own key-up still ends it")

## Two slots can hold hover Actions at once, and `hover_gravity_scale` is
## ONE value they share. Whoever ended first used to write 1.0 over the
## other's claim: that slot stayed `_held`, kept paying its drain, and
## lifted nothing. So the value is derived from every slot's claim rather
## than assigned by whichever spoke last, and the strongest claim holds.
func _two_hovers_at_once_do_not_cancel_each_other() -> void:
	await _reset()
	var a := _runtime("mobility")
	var b := _runtime("utility")
	# The utility slot gets a hover too, a gentler one.
	var second: Dictionary = (BridgeClient.owned_component(
			"act_hover").get("component", {}) as Dictionary).duplicate(true)
	second["component_id"] = "act_hover2"
	second["primitive"] = (second["primitive"] as Dictionary).duplicate()
	second["primitive"]["gravity_multiplier"] = 0.5
	b.set_equipped(second)

	a.activate()
	b.activate()
	await get_tree().physics_frame
	_check(is_equal_approx(_player.hover_gravity_scale, 0.2),
			"the stronger claim holds while both hover: %f"
			% _player.hover_gravity_scale)

	b.release()
	await get_tree().physics_frame
	_check(is_equal_approx(_player.hover_gravity_scale, 0.2),
			"the gentler one ending leaves the stronger claim: %f"
			% _player.hover_gravity_scale)
	_check(a._held, "...and the still-hovering slot is still held")

	a.release()
	await get_tree().physics_frame
	_check(is_equal_approx(_player.hover_gravity_scale, 1.0),
			"the last one ending releases gravity: %f"
			% _player.hover_gravity_scale)

## A parry is a timed answer to something arriving. A tick of
## damage-over-time is neither timed nor arriving -- it is the same status
## bleeding out a sixtieth of a second's worth -- and it used to spend the
## whole window on 0.067 damage of burn. Any DoT made parry unusable, and
## it emitted `parried`, which `main.gd` turns into a free `parry_success`
## rule event: a burn made that event something you could produce by
## standing still.
func _a_burn_tick_does_not_spend_the_parry_window() -> void:
	await _reset()
	var runtime := _runtime("echo_a")
	_parries = 0
	if not runtime.parried.is_connected(_count_parry):
		runtime.parried.connect(_count_parry)
	runtime._parry_window = 0.4
	_player.statuses.apply("burning", 5.0, 1.0)
	for i in range(4):
		await get_tree().physics_frame
	_check(runtime._parry_window > 0.0,
			"the window survives a burning player: %f"
			% runtime._parry_window)
	_check(_player.hp < Constants.PLAYER_MAX_HP,
			"...and the burn is genuinely burning")
	_check(_parries == 0,
			"...and no `parried` is emitted, which main.gd would turn into "
			+ "a free parry_success rule event (%d)" % _parries)

	# A real hit still spends it.
	_player.take_damage(20.0)
	_check(is_equal_approx(runtime._parry_window, 0.0),
			"a real hit still spends the window")
	_check(_parries == 1, "...and reports the parry (%d)" % _parries)
	_player.statuses.clear()

## The shield timer used to decay only while there was shield left on it,
## so a shield absorbed down to nothing froze its timer -- and
## `grant_shield` takes the MAX of the old and new durations, so the next
## grant inherited it. A rule's one-second shield lasted the thirty
## seconds of a shield that had been gone for half a minute.
func _an_absorbed_shield_does_not_inflate_the_next_one() -> void:
	await _reset()
	var runtime := _runtime("echo_a")
	runtime.grant_shield(50.0, 30.0)
	_check(is_equal_approx(runtime.shield_hp, 50.0), "the shield is up")

	# Absorbed away entirely.
	_player.take_damage(50.0)
	_check(is_equal_approx(runtime.shield_hp, 0.0), "and absorbed away")
	for i in range(20):
		await get_tree().physics_frame
	_check(runtime._shield_timer < 30.0,
			"a spent shield's timer keeps decaying: %f"
			% runtime._shield_timer)

	# The interesting half: a new, short shield must be short.
	runtime._shield_timer = 0.0
	runtime.grant_shield(10.0, 1.0)
	_check(is_equal_approx(runtime._shield_timer, 1.0),
			"a one-second shield lasts one second, not thirty: %f"
			% runtime._shield_timer)

## `Player.echo_runtime` is a getter over `highlighted_slot`, and the rule
## engine used to copy its VALUE at bind time -- pinning every rule shield
## and cooldown reset to whichever slot was highlighted when the Zone
## loaded, which is `echo_a`, always.
func _rule_effects_follow_the_slot_the_player_is_looking_at() -> void:
	await _reset()
	var rules := RuleRuntime.new()
	add_child(rules)
	rules.pool = _pool
	rules.player = _player

	_player.set_highlighted_slot("echo_a")
	_check(rules.echo_runtime == _runtime("echo_a"),
			"the rule engine looks at the highlighted slot")
	_player.set_highlighted_slot("mobility")
	_check(rules.echo_runtime == _runtime("mobility"),
			"...and follows it when the player looks elsewhere")

	# And a rule shield lands there, not on echo_a.
	rules._apply_effect("rule_test", {
		"type": "grant_shield", "amount": 25.0, "duration": 5.0})
	_check(is_equal_approx(_runtime("mobility").shield_hp, 25.0),
			"a rule shield lands on the slot being looked at: %f"
			% _runtime("mobility").shield_hp)
	_check(is_equal_approx(_runtime("echo_a").shield_hp, 0.0),
			"...and not on whichever slot loaded first")
	rules.queue_free()
