"""Archipepsi v0.7 — binding constants.

SINGLE SOURCE OF TRUTH for every tunable number. Godot reads the same
values from `constants.gd`, generated by `export.py`. Never hand-edit the
GDScript copy.

Two rules govern this file:

1. Every gameplay number in the design lives here. If a spec document
   states a number that is not in this file, this file wins.

2. Derived constants are *derived*, never typed in. The traversal bounds in
   particular are computed from the jump arc, so retuning movement
   recomputes the guarantee instead of silently invalidating it.

Units: metres, seconds, metres/second. Angles in degrees.
"""

from __future__ import annotations

import hashlib
import math
import random
from dataclasses import dataclass

# --------------------------------------------------------------------------
# Campaign scale — the per-seed options (CAMPAIGN_SCALE.md)
# --------------------------------------------------------------------------
# Scale is a PER-CAMPAIGN choice, not a build-time constant. Two players in
# one multiworld may legitimately pick different sizes, so the numbers below
# describe the space of legal campaigns; a `CampaignConfig` picks one point
# in it and everything else is derived from that point.
#
# Bounds are tested, not advisory. Small values stay reachable for CI, for
# development and for short multiworlds; the frontier runs at both ends.

LOCATION_COUNT_MIN = 30
LOCATION_COUNT_MAX = 600
ZONE_TARGET_CHECKS_MIN = 1
ZONE_TARGET_CHECKS_MAX = 30
ZONE_BUDGET_MIN = 200
ZONE_BUDGET_MAX = 2000

DEFAULT_LOCATION_COUNT = 450
DEFAULT_ZONE_TARGET_CHECKS = 15
DEFAULT_ZONE_BUDGET = 1000

#: The stable id and name universe, fixed at the maximum FOREVER.
#:
#: `Archipepsi Check 007` is id 89100007 in every seed ever generated,
#: whatever anyone chose for `location_count`. A world instantiates a PREFIX
#: of this universe; it never renumbers an existing location because
#: somebody picked a different campaign size. Raising this is a deliberate,
#: versioned change -- every seed generated before the change keeps ids that
#: must still mean the same Checks.
LOCATION_UNIVERSE = LOCATION_COUNT_MAX

#: Item-pool proportions, preserved from the prototype's 2 / 10 / 18 of 30.
#: Signal Keys are fixed by the tier count (N tiers need N-1 unlocks), so
#: the split applies to what is left. Static takes the remainder, which is
#: what makes the pool EXACTLY equal the location count at any size rather
#: than one item short after rounding.
COIN_SHARE_OF_NON_KEY = 10 / 28

#: The least content a Zone must be worth per Check it is asked to hold.
#:
#: Every Check needs a room, and a room the player crosses to reach a
#: pedestal is worth something whether or not anybody budgeted for it. So
#: `zone_target_checks` and `zone_budget` are not independent, even
#: though they are separate options: 15 Checks in a 200-point Zone is a
#: configuration that cannot be built, and the honest place to say so is
#: at generation rather than when a player's portal refuses to open.
#:
#: Measured rather than guessed: the fallback's Check rooms score in the
#: mid-twenties once they have an objective and a small encounter, and
#: 25 is the floor of that.
MIN_BUDGET_PER_CHECK = 25

#: The finale opens after a substantial majority of non-goal Checks.
#:
#: 0.8 rather than the prototype's literal 24: `ceil(29 * 0.8) == 24`, so
#: an existing campaign keeps exactly the requirement it was generated
#: with, and a 450-location campaign gets 360 instead of a number that
#: stopped meaning "a substantial majority" the moment the campaign grew.
FINALE_REQUIRED_FRACTION = 0.8


@dataclass(frozen=True)
class CampaignConfig:
    """One campaign's immutable scale. Chosen at generation, never in play.

    Frozen and dependency-free on purpose: this module is vendored verbatim
    into the APWorld, which runs inside Archipelago and cannot import
    pydantic. Validation is therefore hand-written rather than declarative.
    """

    location_count: int = DEFAULT_LOCATION_COUNT
    zone_target_checks: int = DEFAULT_ZONE_TARGET_CHECKS
    zone_budget: int = DEFAULT_ZONE_BUDGET

    def __post_init__(self) -> None:
        for name, low, high in (
            ("location_count", LOCATION_COUNT_MIN, LOCATION_COUNT_MAX),
            ("zone_target_checks", ZONE_TARGET_CHECKS_MIN,
             ZONE_TARGET_CHECKS_MAX),
            ("zone_budget", ZONE_BUDGET_MIN, ZONE_BUDGET_MAX),
        ):
            value = getattr(self, name)
            if not isinstance(value, int) or isinstance(value, bool):
                raise ValueError(f"{name} must be an int, got {value!r}")
            if not low <= value <= high:
                raise ValueError(
                    f"{name}={value} is outside the tested range "
                    f"[{low}, {high}]. Widening it is a deliberate change "
                    f"to CAMPAIGN_SCALE.md, not a call site's decision.")
        # A campaign needs at least one ordinary Check to allocate, or the
        # only location is the goal and the finale gate can never open.
        if self.location_count <= 1:
            raise ValueError("a campaign needs a non-goal Check")
        # ...and a Zone must be able to HOLD the Checks it is given.
        needed = self.zone_target_checks * MIN_BUDGET_PER_CHECK
        if self.zone_budget < needed:
            raise ValueError(
                f"zone_budget={self.zone_budget} cannot hold "
                f"zone_target_checks={self.zone_target_checks}: every "
                f"Check needs a room, so this Zone needs at least "
                f"{needed} points of content. Raise the budget or lower "
                "the Checks per Zone.")

    # -- the active id range ------------------------------------------------

    @property
    def first_location_id(self) -> int:
        return LOCATION_ID_BASE + 1

    @property
    def last_location_id(self) -> int:
        return LOCATION_ID_BASE + self.location_count

    @property
    def goal_location_id(self) -> int:
        """The FINAL ACTIVE location, so it moves with campaign size.

        Every other id is stable across seeds; this one is not, and that is
        the price of the goal being at the end. The end is what makes "any
        location except the goal" a closed range expressible in JSON Schema
        and GDScript instead of only in a Python validator.
        """
        return self.last_location_id

    @property
    def non_goal_count(self) -> int:
        return self.location_count - 1

    def is_goal_location(self, location_id: int) -> bool:
        return location_id == self.goal_location_id

    def active_location_ids(self) -> list[int]:
        return list(range(self.first_location_id, self.last_location_id + 1))

    # -- tiers --------------------------------------------------------------

    def tier_bounds(self) -> tuple[int, ...]:
        """Half-open bounds; tier N holds [bounds[N], bounds[N + 1]).

        Split as evenly as the count allows, with the remainder going to the
        earliest tiers. The sum is exact by construction, so no location can
        fall outside every tier.
        """
        base, extra = divmod(self.location_count, TIER_COUNT)
        bounds = [self.first_location_id]
        for tier in range(TIER_COUNT):
            bounds.append(bounds[-1] + base + (1 if tier < extra else 0))
        return tuple(bounds)

    def tier_of(self, location_id: int) -> int:
        if not self.first_location_id <= location_id <= self.last_location_id:
            raise ValueError(f"{location_id} is not an Archipepsi location")
        bounds = self.tier_bounds()
        for tier in range(TIER_COUNT):
            if bounds[tier] <= location_id < bounds[tier + 1]:
                return tier
        raise ValueError(f"{location_id} fell outside every tier")

    def locations_in_tier(self, tier: int) -> list[int]:
        bounds = self.tier_bounds()
        return list(range(bounds[tier], bounds[tier + 1]))

    def unlocked_location_ids(self, signal_keys: int) -> list[int]:
        """Everything AP logic considers reachable. INCLUDES the goal."""
        unlocked = min(signal_keys, TIER_COUNT - 1)
        return list(range(self.first_location_id,
                          self.tier_bounds()[unlocked + 1]))

    def eligible_location_ids(self, signal_keys: int) -> list[int]:
        """Everything an ordinary Zone or the shop may allocate. Never the
        goal. The single entry point for allocation."""
        return [i for i in self.unlocked_location_ids(signal_keys)
                if not self.is_goal_location(i)]

    # -- allocation ---------------------------------------------------------

    @property
    def zone_min_checks(self) -> int:
        """Below this, a Zone is padded from another track.

        A campaign can be configured at one Check per Zone, and a floor
        of two would then be unsatisfiable -- so the floor is whichever
        is smaller.
        """
        return min(ZONE_MIN_CHECKS, self.zone_target_checks)

    @property
    def shop_reserve(self) -> int:
        """Checks the shop leaves in the pool for the next Zone.

        One Zone's worth, which is a per-campaign number: reserving the
        prototype's three in a fifteen-Check campaign lets the shop
        strip a Zone down to a fifth of its length.
        """
        return self.zone_target_checks

    # -- finale -------------------------------------------------------------

    def zone_budget_for(self, allocated_checks: int) -> int:
        """The budget for a Zone holding this many Checks.

        The LAST Zone of a campaign is a remainder: 449 Checks at 15 per
        Zone leaves a short one, and holding it to a full 1000 points
        would demand a forty-minute level built around two pedestals.

        So the budget scales with what the Zone was actually given, and
        is floored at the minimum: a one-Check Zone is a short level, not
        a broken one.
        """
        if allocated_checks >= self.zone_target_checks:
            return self.zone_budget
        share = allocated_checks / max(1, self.zone_target_checks)
        return max(ZONE_BUDGET_MIN, round(self.zone_budget * share))

    def finale_required_checks(self) -> int:
        """Non-goal Checks needed before the finale is offered."""
        return math.ceil(self.non_goal_count * FINALE_REQUIRED_FRACTION)

    # -- item pool ----------------------------------------------------------

    def item_counts(self) -> dict[str, int]:
        """Exactly `location_count` items. Static takes the remainder."""
        keys = min(SIGNAL_KEY_COUNT, self.location_count)
        rest = self.location_count - keys
        coins = round(rest * COIN_SHARE_OF_NON_KEY)
        static = rest - coins
        counts = {
            ITEM_NAME_SIGNAL_KEY: keys,
            ITEM_NAME_EPSILON_COIN: coins,
            ITEM_NAME_EPSILON_STATIC: static,
        }
        assert sum(counts.values()) == self.location_count
        return counts


#: What a campaign generated before these options existed WAS.
#:
#: A save or slot with no recorded config migrates to this and never to the
#: production default. Reinterpreting an old 30-location campaign as 450
#: would invent 420 locations the seed never had and strand every item the
#: multiworld placed on them. `zone_budget` is the floor because the
#: prototype enforced no budget at all; it is a placeholder for a value that
#: did not exist, not a claim that old Zones were worth 200.
PROTOTYPE_CONFIG = CampaignConfig(
    location_count=30, zone_target_checks=3, zone_budget=ZONE_BUDGET_MIN)

DEFAULT_CONFIG = CampaignConfig()


# --------------------------------------------------------------------------
# Campaign shape — PROTOTYPE constants, being migrated to CampaignConfig
# --------------------------------------------------------------------------
# These are the prototype campaign's numbers and remain the values the
# not-yet-migrated call sites use. `test_campaign_config.py` pins every one
# of them to `PROTOTYPE_CONFIG`, so the two cannot drift while the migration
# is in progress; they are deleted as their callers move over.

LOCATION_COUNT = 30
LOCATION_ID_BASE = 89_100_000
ITEM_ID_BASE = 89_200_000

FIRST_LOCATION_ID = LOCATION_ID_BASE + 1              # 89100001
LAST_LOCATION_ID = LOCATION_ID_BASE + LOCATION_COUNT  # 89100030
GOAL_LOCATION_ID = LAST_LOCATION_ID                   # Check 030

#: The highest id the universe reaches. Every persistent model is bounded by
#: THIS rather than by one campaign's last location, so a save can hold
#: whichever prefix its own seed was generated with.
LAST_UNIVERSE_ID = LOCATION_ID_BASE + LOCATION_UNIVERSE

# --------------------------------------------------------------------------
# The goal reservation — ONE definition, used by every path
# --------------------------------------------------------------------------
# v0.5 stated "Check 030 is never shop stock, never a normal Zone reward" in
# five prose locations and enforced it in exactly one model validator, on the
# Zone path. Shop stock, the purchase intent and the pending-transaction
# record all accepted it, so `6 coins -> buy Check 030 -> win` was a legal
# message sequence. The rule now lives here and every reservation-capable
# field derives from it, so a neighbouring path cannot diverge again.

#: The goal is deliberately the LAST location id. That makes "any location
#: except the goal" a plain closed range, which is expressible in JSON Schema
#: and GDScript rather than only in a Python validator — so the constraint
#: survives export to the provider schema and to the engine. If the goal ever
#: moves off the end, this assert fires instead of the range silently
#: admitting Check 030 again.
assert GOAL_LOCATION_ID == LAST_LOCATION_ID, (
    "NON_FINALE_LOCATION range assumes the goal is the highest location id"
)
FIRST_NON_FINALE_LOCATION_ID = FIRST_LOCATION_ID
LAST_NON_FINALE_LOCATION_ID = GOAL_LOCATION_ID - 1    # 89100029


def is_goal_location(location_id: int) -> bool:
    """True for the one location reachable ONLY through the finale Zone."""
    return location_id == GOAL_LOCATION_ID

# v0.5 terminology: the soda pun survives only in the project codename.
ITEM_NAME_SIGNAL_KEY = "Signal Key"
ITEM_NAME_EPSILON_COIN = "Epsilon Coin"
ITEM_NAME_EPSILON_STATIC = "Epsilon Static"

ITEM_ID_SIGNAL_KEY = ITEM_ID_BASE + 1                 # 89200001
ITEM_ID_EPSILON_COIN = ITEM_ID_BASE + 2               # 89200002
ITEM_ID_EPSILON_STATIC = ITEM_ID_BASE + 3             # 89200003

SIGNAL_KEY_COUNT = 2
EPSILON_COIN_COUNT = 10
EPSILON_STATIC_COUNT = 18
assert SIGNAL_KEY_COUNT + EPSILON_COIN_COUNT + EPSILON_STATIC_COUNT == LOCATION_COUNT

# --------------------------------------------------------------------------
# Tiers — the mirror APWORLD_SPEC points at (v0.4 referenced an undefined name)
# --------------------------------------------------------------------------

TIER_SIZE = 10
TIER_COUNT = 3

#: Half-open bounds. Tier N holds [TIER_BOUNDS[N], TIER_BOUNDS[N + 1]).
TIER_BOUNDS = tuple(
    FIRST_LOCATION_ID + i * TIER_SIZE for i in range(TIER_COUNT + 1)
)
assert TIER_BOUNDS[-1] == LAST_LOCATION_ID + 1


def tier_of(location_id: int) -> int:
    """Which tier a location belongs to. Tier N requires N Signal Keys."""
    if not FIRST_LOCATION_ID <= location_id <= LAST_LOCATION_ID:
        raise ValueError(f"{location_id} is not an Archipepsi location")
    return (location_id - FIRST_LOCATION_ID) // TIER_SIZE


def locations_in_tier(tier: int) -> list[int]:
    return list(range(TIER_BOUNDS[tier], TIER_BOUNDS[tier + 1]))


def unlocked_location_ids(signal_keys: int) -> list[int]:
    """Every location Archipelago logic considers REACHABLE at this key count.

    This is the region-rule view and it includes the goal, because to
    Archipelago Check 030 is an ordinary location in Tier 2. The APWorld
    region rules and the slot-data `tiers` block derive from this.

    It is NOT the allocator's view. Nothing that reserves, stocks, prices or
    hands out a location may call this — Check 030 is reserved for the finale
    Zone. Allocators call `eligible_location_ids()`. v0.5's docstring said
    "legal to allocate ... goal included" on the one helper the packet told
    implementers to derive from, which is how the shop got the goal.
    """
    unlocked = min(signal_keys, TIER_COUNT - 1)
    return list(range(FIRST_LOCATION_ID, TIER_BOUNDS[unlocked + 1]))


def eligible_location_ids(signal_keys: int) -> list[int]:
    """Every location an ORDINARY Zone or the shop may allocate. Never the goal.

    The single entry point for allocation. Ordinary Zone selection, shop
    restock, the fallback Zone builder and the reconciliation pass that
    returns abandoned locations to the pool all start here — none of them
    re-derives the candidate set, and none of them may add the goal back.

    The finale Zone does not use this function: it is handed exactly
    `[GOAL_LOCATION_ID]` by the finale path, gated on
    `FINALE_REQUIRED_SIGNAL_KEYS` and `FINALE_REQUIRED_OTHER_CHECKS`.
    """
    return [i for i in unlocked_location_ids(signal_keys)
            if not is_goal_location(i)]


# --------------------------------------------------------------------------
# Finale and postgame
# --------------------------------------------------------------------------

FINALE_REQUIRED_SIGNAL_KEYS = 2
FINALE_REQUIRED_OTHER_CHECKS = 24     # of the 29 non-goal Checks

#: v0.5: sending goal does NOT end play. Remaining Checks stay reachable
#: through the Hub until cleared or the player stops. Abandoning real AP
#: locations because the goal fired would strand other players' items.
POSTGAME_ENABLED = True

# --------------------------------------------------------------------------
# Zone allocation
# --------------------------------------------------------------------------

#: The PROTOTYPE's allocation shape, kept because a save written before
#: the options is a prototype campaign and has to keep behaving like one.
#: The live numbers come from the campaign's own `CampaignConfig`
#: (CAMPAIGN_SCALE.md 2) -- a campaign at fifteen Checks per Zone that
#: allocated three would be a 450-location campaign played at prototype
#: density, which is the whole thing the options exist to change.
ZONE_TARGET_CHECKS = 3
ZONE_MAX_CHECKS = 3
ZONE_MIN_CHECKS = 2       # 1 only when exactly one eligible Check remains
#: The engine's ceiling on rooms in one Zone, NOT the composition target
#: (CAMPAIGN_SCALE.md 7).
#:
#: Six was the prototype's shape, and it stopped a 1000-point Zone from
#: existing at all: fifteen Checks capped at three per room need five
#: rooms before a single corridor, fight or quiet space is added. This is
#: now a safety limit -- the point past which a Zone stops being a level
#: and starts being a memory problem -- and nothing should be designing
#: toward it.
ZONE_MAX_CHAMBERS = 40
ZONE_MIN_CHAMBERS = 1

#: Advisory room count for a budget, which is what Epsilon is TOLD.
#:
#: An envelope, not a rule: a Zone may be fewer large complicated spaces
#: or more small ones, provided the content budget and the composition
#: constraints hold. Deliberately not validated -- validating it would
#: make it the rule it is explicitly not, and the thing that actually
#: matters (is there enough real content, and is it varied) is checked
#: directly.
ROOMS_PER_BUDGET_POINT = 15 / 1000


def zone_room_envelope(zone_budget: int) -> tuple[int, int]:
    """Roughly how many meaningful spaces a Zone of this size wants."""
    middle = zone_budget * ROOMS_PER_BUDGET_POINT
    return (max(ZONE_MIN_CHAMBERS, round(middle * 0.7)),
            min(ZONE_MAX_CHAMBERS, round(middle * 1.35)))

#: The narrowest chamber each affordance tag can be built in (ECHOES 13.2).
#:
#: A feature must sit clear of the walking lane, and the client's builder
#: is what enforces that in metres: `2 * (2.0 lane + 2 * reach + 0.35 wall
#: clearance)`. The reach is counted TWICE because a feature spans it on
#: each side of its origin — the origin must clear the lane by a reach AND
#: stay a reach inside the wall, and only a width covering both leaves
#: anywhere to put it.
#:
#: Per tag rather than one number, because the tags are not the same size:
#: a rail needs 6.7 m and a water volume 7.9 m. A
#: single conservative constant would refuse the rail from every corridor
#: the wind column could not fit in either, which is content lost for no
#: reason.
#:
#: Validated rather than left to the builder to drop, because a silently
#: discarded feature is a Zone that reads richer than it plays — and a
#: refusal is something the repair loop can fix. Pinned against
#: `AffordanceFeatures.FOOTPRINT` from both sides in `test_affordances.py`.
FEATURE_MIN_WIDTH = {
    "grapple_anchor": 7.5,
    "breakable_wall": 7.5,
    "water_volume": 7.9,
    "rail": 6.7,
    "wind_volume": 7.9,
    "bounce_pad": 7.1,
    "moving_platform": 7.9,
}

#: The narrowest chamber that can host ANY feature — the cheapest thing a
#: generator can check before choosing a tag.
MIN_FEATURE_CHAMBER_WIDTH = min(FEATURE_MIN_WIDTH.values())

# --------------------------------------------------------------------------
# Shop
# --------------------------------------------------------------------------

SHOP_STOCK_SIZE = 2
SHOP_FIRST_STOCK_AFTER_ZONES = 2
SHOP_RESTOCK_EVERY_ZONES = 2
SHOP_PRICE_PROGRESSION = 6
SHOP_PRICE_USEFUL = 4
SHOP_PRICE_OTHER = 2
SHOP_MIN_REMAINING_AFTER_STOCK = ZONE_TARGET_CHECKS


def shop_stock_seed(seed_name: str, team: int, slot_id: int,
                    completed_zone_count: int) -> tuple:
    """Seed for shop restock selection.

    v0.6 called stock selection "deterministic" and supplied no seed, leaving
    the third hand-rolled shuffle in a packet whose own DESIGN §10.3 names
    that omission as a v0.3 defect. Same shape as the other two recipes;
    `completed_zone_count` is the restock discriminator because the cadence
    is driven by it.
    """
    return (seed_name, team, slot_id, completed_zone_count, "shop_stock")

# AP NetworkItem.flags bits
FLAG_PROGRESSION = 0b001
FLAG_USEFUL = 0b010
FLAG_TRAP = 0b100

# --------------------------------------------------------------------------
# Player movement
# --------------------------------------------------------------------------

GRAVITY = 24.0
WALK_SPEED = 7.0
JUMP_VELOCITY = 8.0
COYOTE_TIME = 0.12
JUMP_BUFFER = 0.10
AIR_CONTROL = 0.4

PLAYER_HEIGHT = 1.8
PLAYER_RADIUS = 0.4
PLAYER_EYE_HEIGHT = 1.6

FALL_KILL_Y = -30.0
RESPAWN_DELAY = 1.5

#: An enemy below this counts as dead. Without it, one enemy steered off a
#: tower floor leaves `kill_all` unsatisfiable and the Zone unfinishable.
ENEMY_FALL_KILL_Y = FALL_KILL_Y

# --------------------------------------------------------------------------
# Passive Echo bounds — constrained BY the traversal guarantee
# --------------------------------------------------------------------------
# v0.4 bounded these independently, which let a legal passive Echo make a
# mandatory gap uncrossable: gravity 1.5 dropped jump apex to 0.89 m against
# a 1.0 m mandatory step. The schema forbade positive Echo gates and
# permitted negative ones.
#
# Gravity multipliers may only ever REDUCE gravity, so a gravity Echo is
# always a help. Speed has a floor tight enough that the worst legal
# loadout still clears every mandatory gap.

GRAVITY_MULT_MIN = 0.35
GRAVITY_MULT_MAX = 1.0
SPEED_MULT_MIN = 0.9
SPEED_MULT_MAX = 1.6

# --------------------------------------------------------------------------
# Traversal — derived, and derived for the WORST legal loadout
# --------------------------------------------------------------------------

JUMP_APEX_HEIGHT = JUMP_VELOCITY ** 2 / (2 * GRAVITY)     # 1.333 m
JUMP_AIRTIME = 2 * JUMP_VELOCITY / GRAVITY                # 0.667 s
JUMP_FLAT_REACH = WALK_SPEED * JUMP_AIRTIME               # 4.667 m

#: Margin against imperfect timing, approach angle and air control.
SAFE_GAP_MARGIN = 0.64
SAFE_STEP_MARGIN = 0.75


def _floor1(x: float) -> float:
    """Floor to one decimal. A safety bound must never round upward."""
    return math.floor(x * 10.0) / 10.0


def jump_reach(vertical_step: float = 0.0,
               gravity_mult: float = GRAVITY_MULT_MAX,
               speed_mult: float = SPEED_MULT_MIN) -> float:
    """Horizontal distance covered landing `vertical_step` above takeoff.

    Defaults are the worst legal loadout, so callers get the pessimistic
    answer unless they deliberately ask otherwise.
    """
    g = GRAVITY * gravity_mult
    disc = JUMP_VELOCITY ** 2 - 2 * g * vertical_step
    if disc < 0:
        return 0.0
    return WALK_SPEED * speed_mult * (JUMP_VELOCITY + math.sqrt(disc)) / g


def max_safe_gap(vertical_step: float = 0.0) -> float:
    """Largest gap a mandatory jump may span at this landing height.

    v0.4 bounded gap and step independently, so both could be maxed: the
    real margin was 1.17x, not the 1.56x the flat-jump derivation claimed.
    This is the joint bound.
    """
    return _floor1(jump_reach(vertical_step) * SAFE_GAP_MARGIN)


#: Flat-ground bound. Chambers with a vertical step get a tighter one.
SAFE_BASE_JUMP_GAP = max_safe_gap(0.0)

#: Apex under the worst legal loadout, with margin.
MAX_VERTICAL_STEP = _floor1(
    JUMP_VELOCITY ** 2 / (2 * GRAVITY * GRAVITY_MULT_MAX) * SAFE_STEP_MARGIN
)
MIN_PLATFORM_SIZE = 2.5

# --------------------------------------------------------------------------
# Combat
# --------------------------------------------------------------------------

PLAYER_MAX_HP = 100.0

#: Static Pulse: LMB, always available, never replaced by an equipped Echo.
STATIC_PULSE_DAMAGE = 6.0
STATIC_PULSE_COOLDOWN = 0.35
STATIC_PULSE_RANGE = 40.0
STATIC_PULSE_DPS = STATIC_PULSE_DAMAGE / STATIC_PULSE_COOLDOWN   # ~17.1

ENEMY_STATS = {
    "melee":  {"hp": 24.0,  "damage": 6.0,  "cooldown": 1.0, "speed": 4.0, "reach": 2.0},
    "ranged": {"hp": 16.0,  "damage": 8.0,  "cooldown": 2.0, "speed": 0.0, "reach": 40.0},
    "brute":  {"hp": 120.0, "damage": 18.0, "cooldown": 1.6, "speed": 2.2, "reach": 2.5},
}
ENEMY_AGGRO_RADIUS = 18.0
RANGED_PROJECTILE_SPEED = 14.0

# --------------------------------------------------------------------------
# Combat scale (CAMPAIGN_SCALE.md 8)
# --------------------------------------------------------------------------
# These were one number, `MAX_ENEMIES_PER_ZONE = 14`, doing four jobs:
# how many the player meets, how many are alive at once, how long the
# shooting lasts, and what the engine can afford. That works while a Zone
# is six rooms and every enemy in it is effectively one fight. It cannot
# describe a forty-minute level, and replacing 14 with a bigger number
# would just make the conflation bigger.
#
# So they separate. Two of them SCALE with the Zone's content budget --
# a longer level has more enemies in it over time -- and two do NOT,
# because they are about a single moment: what is on screen, and what the
# player is being asked to survive right now.

#: Enemies in one encounter group, and how many of those may be brutes.
#: This is the unit a player actually fights, and it does not grow with
#: the level: a 40-minute Zone is more fights, not a bigger fight.
#: Seconds a player needs per activity element at base movement speed,
#: used to floor a timed puzzle's clock. Derived from the walk across a
#: mid-size room plus the interaction itself, generously: a puzzle that
#: is tight for a good player is fine, one that is impossible for the
#: base kit is a wall.
SECONDS_PER_ACTIVITY_ELEMENT = 4.0

#: Ordered puzzles cost more time because a mistake means going back.
ORDERED_ACTIVITY_TIME_MULTIPLIER = 1.5

MAX_ENEMIES_PER_ENCOUNTER = 10
MAX_BRUTES_PER_ENCOUNTER = 1

#: Alive and hostile at the same instant, across the whole Zone. Bounded
#: for fairness first and frame time second -- a player cannot read
#: thirty telegraphs, whatever the renderer can manage.
MAX_ENEMIES_ACTIVE = 12

#: One room, over the whole time the player is in it. Larger than an
#: encounter because a big arena may hold two or three waves.
MAX_ENEMIES_PER_CHAMBER = 12

#: The hard engine ceiling on enemies instantiated for one Zone. Not a
#: design number: a design that wants more is wrong about what the target
#: machine can hold, and should say so by failing here.
MAX_ENEMIES_SPAWNED_CAP = 240

#: How the two scaling caps derive from `zone_budget`.
#:
#: Both reproduce the prototype EXACTLY at the 200-point floor -- 14
#: enemies, 1 brute -- so a campaign generated before budgets existed
#: keeps the combat it was built with, the same property CampaignConfig
#: has for tiers and the item pool.
ENEMIES_PER_BUDGET_POINT = 14 / 200
BRUTES_PER_BUDGET_POINT = 1 / 200


def max_enemies_per_zone(zone_budget: int) -> int:
    """Total enemies a Zone may contain, over its whole length.

    NOT how many are alive at once -- that is `MAX_ENEMIES_ACTIVE`, and
    conflating the two is what made the old single number unable to
    describe a long level.
    """
    return min(MAX_ENEMIES_SPAWNED_CAP,
               round(zone_budget * ENEMIES_PER_BUDGET_POINT))


def max_brutes_per_zone(zone_budget: int) -> int:
    return max(1, round(zone_budget * BRUTES_PER_BUDGET_POINT))


#: Seconds of sustained Static Pulse fire the worst legal ENCOUNTER may
#: need. Per encounter, because "the whole level equals 40 seconds of
#: shooting" stopped being a statement about difficulty the moment a Zone
#: became forty minutes long -- it would have capped a production Zone at
#: about the combat of one arena.
WORST_CASE_ENCOUNTER_TTK_BUDGET = 40.0


def worst_case_encounter_ttk() -> float:
    """Seconds to clear the worst legal single encounter with the base kit."""
    brute_hp = ENEMY_STATS["brute"]["hp"] * MAX_BRUTES_PER_ENCOUNTER
    grunts = MAX_ENEMIES_PER_ENCOUNTER - MAX_BRUTES_PER_ENCOUNTER
    grunt_hp = ENEMY_STATS["melee"]["hp"] * grunts
    return (brute_hp + grunt_hp) / STATIC_PULSE_DPS


# --------------------------------------------------------------------------
# Echo bounds
# --------------------------------------------------------------------------

ECHO_EFFECTS_MIN = 1
ECHO_EFFECTS_MAX = 3
ECHO_COOLDOWN_MIN = 0.15
ECHO_COOLDOWN_MAX = 15.0

#: ECHOES.md §5.1: rule firings per physics tick, globally capped. The
#: termination argument needs a finite bound stated somewhere both languages
#: can read; 8 is generous against the hard rule budget of 20 given every
#: rule also carries a mandatory 0.1 s cooldown.
RULE_FIRINGS_PER_TICK_CAP = 8

#: The hp fraction under which the engine derives `low_health`, on the
#: crossing edge only. One shared number so a rule, the HUD and Epsilon's
#: worried voice line cannot disagree about what "low" means.
LOW_HEALTH_FRACTION = 0.33

#: The envelope every non-traversal derived stat is clamped into after the
#: whole stack multiplies out (traits x scales links x statuses x pulses).
#: One trait is schema-bounded to [0.1, 4.0]; the STACK needs its own bound
#: or four stacked traits could reach 256x. Traversal stats have the harder
#: rule (floored at base, speed/gravity to their own caps) and ignore this.
STAT_STACK_MIN = 0.25
STAT_STACK_MAX = 4.0

#: The four Action slots (ECHOES.md §9). Here rather than only in
#: `echo.py` because the CLIENT binds one key per slot and builds one
#: action runtime per slot: a slot the schema admits and no key reaches is
#: an Action you own and cannot press, which is the failure
#: `IMPLEMENTED_ACTION_SLOTS` exists to prevent. Exported to GDScript, so
#: the two sides cannot disagree about how many there are.
SLOT_NAMES = ("echo_a", "echo_b", "mobility", "utility")

#: Reference mid-bounds Echo, used to state the Static Pulse comparison
#: honestly. The *bounds* permit far more; a typical Echo lands near this.
REFERENCE_ECHO_DAMAGE = 12.0
REFERENCE_ECHO_PELLETS = 3
REFERENCE_ECHO_COOLDOWN = 0.8

# --------------------------------------------------------------------------
# Epsilon
# --------------------------------------------------------------------------

#: Late-90s PC FPS material sets, one per source game. Not voxel palettes:
#: chunky brushwork, grime, harsh lights, industrial fittings.
THEMES = (
    "concrete_facility",   # bright test-chamber facility, clean concrete, vents
    "rusted_industrial",   # oil-drum desert refinery, corrugated steel, scaffold
    "neon_transit",        # underground station, tile, signage, neon spill
    "gothic_stone",        # chunky castle stone, iron, torchlight
    "temple_ruin",         # cracked sandstone, root intrusion, brass fittings
    "void_glitch",         # untextured dev surfaces, missing-texture checker
)
CHAMBER_TYPES = ("corridor", "arena", "platform_path", "tower", "treasure_room")
ENEMY_ARCHETYPES = ("melee", "ranged", "brute")
OBJECTIVES = ("reach_reward", "kill_all", "platform_to_goal")

THEME_BY_GAME_HINT = {
    "Super Mario 64": "concrete_facility",
    "Ocarina of Time": "temple_ruin",
    "Bomb Rush Cyberfunk": "neon_transit",
    "Dark Souls III": "gothic_stone",
    "Borderlands 2": "rusted_industrial",
    "Archipepsi": "void_glitch",
}

#: What a theme actually IS at runtime: a palette plus surface parameters the
#: texture generator and the level materials read. v0.5 named six themes and
#: described them only in a comment, leaving ~40 numbers for the implementer
#: to invent — six themes that all render as the same grey box is the likely
#: outcome, and it is not a failure any test would catch.
#:
#: Colors are sRGB hex. `noise` names a generator in our own procedural
#: texture code, never an imported asset (no Blender, no asset shopping).
#: `light_energy` is the Godot OmniLight3D energy for the theme's fixtures.
THEME_MATERIAL_KEYS = (
    "base_color", "accent_color", "trim_color",
    "light_color", "light_energy", "roughness", "noise",
)

THEME_MATERIALS = {
    "concrete_facility": {
        "base_color": "#b9bcb6", "accent_color": "#4f6f8f",
        "trim_color": "#2e3338", "light_color": "#eaf2ff",
        "light_energy": 3.0, "roughness": 0.85, "noise": "speckle",
    },
    "rusted_industrial": {
        "base_color": "#8a5a3b", "accent_color": "#c8722c",
        "trim_color": "#3d2a1e", "light_color": "#ffd9a0",
        "light_energy": 2.2, "roughness": 0.95, "noise": "rust",
    },
    "neon_transit": {
        "base_color": "#d8d4c8", "accent_color": "#18b7c4",
        "trim_color": "#1b1d26", "light_color": "#7cf2ff",
        "light_energy": 4.0, "roughness": 0.35, "noise": "tile",
    },
    "gothic_stone": {
        "base_color": "#6b6560", "accent_color": "#3a3f4a",
        "trim_color": "#241f1c", "light_color": "#ffb45e",
        "light_energy": 2.0, "roughness": 0.9, "noise": "brick",
    },
    "temple_ruin": {
        "base_color": "#c2a878", "accent_color": "#5f7a4a",
        "trim_color": "#7a6034", "light_color": "#ffe9b8",
        "light_energy": 2.6, "roughness": 0.8, "noise": "sandstone",
    },
    "void_glitch": {
        "base_color": "#2b2b3a", "accent_color": "#ff00e6",
        "trim_color": "#00ffbf", "light_color": "#ffffff",
        "light_energy": 3.5, "roughness": 0.5, "noise": "checker",
    },
}
assert tuple(THEME_MATERIALS) == THEMES, "THEME_MATERIALS must cover THEMES in order"
assert all(tuple(m) == THEME_MATERIAL_KEYS for m in THEME_MATERIALS.values()), (
    "every theme defines exactly THEME_MATERIAL_KEYS, in order"
)

#: Procedural texture resolution. v0.4 pinned 16x16 to make life easy for a
#: local model, but Epsilon never paints textures - our code generates them,
#: so the constraint bought nothing and cost the late-90s look.
TEXTURE_SIZE_MIN = 32
TEXTURE_SIZE_MAX = 128
TEXTURE_SIZE_DEFAULT = 64

#: The bridge's local WebSocket endpoint. v0.6 stated it in prose only, so
#: Godot and Python each hard-coded it -- the drift `constants.gd` exists to
#: prevent, in the one constant both sides must agree on to talk at all.
BRIDGE_HOST = "127.0.0.1"
BRIDGE_PORT = 38290

PROVIDER_TIMEOUT_SECONDS = 60.0
REPAIR_ATTEMPTS = 1

#: Local rewards a campaign may hold. Named rather than inlined because
#: the bound is enforced in two places: the model, and the transition that
#: refuses the one after the last so a caller gets a `ValueError` like
#: every other refusal rather than a `ValidationError` from a rebuild.
#: Operations one interpretation may carry (ECHOES §2). Named because a
#: provider that APPENDS an operation has to know whether there is room,
#: and hardcoding 4 in a second place is how the two drift.
ECHO_MAX_OPERATIONS = 4

MAX_LOCAL_REWARDS = 120

MAX_TEXT_LEN = 160
MAX_DESIGNER_NOTE_LEN = 300
MAX_AP_STRING_LEN = 96

# --------------------------------------------------------------------------
# Epsilon Static
# --------------------------------------------------------------------------

STATIC_GLITCH_UNITS_PER_ITEM = 1
STATIC_GLITCH_VISUAL_CAP = 18


# --------------------------------------------------------------------------
# Determinism
# --------------------------------------------------------------------------

def prng_seed(*parts: object) -> int:
    """Stable 64-bit seed from a campaign key.

    Never use Python's built-in hash(): it is randomized per process.
    """
    key = "|".join(str(p) for p in parts)
    return int.from_bytes(hashlib.sha256(key.encode("utf-8")).digest()[:8], "big")


def deterministic_shuffle(items: list, *seed_parts: object) -> list:
    """Fisher-Yates over a seeded Mersenne Twister. Returns a new list.

    Descending index, j = rng.randrange(i + 1). Any reimplementation must
    match exactly, including loop direction. Pinned by test.
    """
    rng = random.Random(prng_seed(*seed_parts))
    out = list(items)
    for i in range(len(out) - 1, 0, -1):
        j = rng.randrange(i + 1)
        out[i], out[j] = out[j], out[i]
    return out


def track_order_seed(seed_name: str, team: int, slot_id: int) -> tuple:
    return (seed_name, team, slot_id, "track_order")


def zone_selection_seed(seed_name: str, team: int, slot_id: int,
                        generation_counter: int, target_game: str) -> tuple:
    """Same tuple shape as track_order_seed plus the per-Zone discriminators.

    v0.4 dropped `team` here, so two slots on different teams with the same
    slot_id got identical Zone shuffles.
    """
    return (seed_name, team, slot_id, generation_counter, target_game)
