#!/usr/bin/env python3
"""THIRD_PARTY_NOTICES.txt for the diagnostic build.

The repository's own `THIRD_PARTY_NOTICES.md` covers ASSETS, generated
from `assets/LICENSES.json` (`make notices`). A shipped build carries
more than assets: the Godot engine it is built on, the CPython it
bundles, the two Python libraries inside it and the MinGW-w64 runtime the
starter links. None of those is an asset, so none of them belongs in that
manifest -- and a Godot export without Godot's MIT notice is the one
licence failure this build could actually make.

So this collects, verbatim where a licence text exists:

  * the asset notices, as committed;
  * Godot's LICENSE.txt and its full COPYRIGHT.txt (third-party
    components the engine itself carries);
  * CPython's LICENSE.txt, out of the embeddable package;
  * each bundled wheel's own metadata licence, read from its
    `.dist-info` -- never retyped here;
  * the MinGW-w64 runtime's copyright file, pointed to rather than
    inlined (it is 100 kB of per-file records) with its licence named.

Every path is given on the command line, so this file states no fact it
cannot show.
"""

from __future__ import annotations

import argparse
import email
import pathlib
import sys

RULE = "=" * 72


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").strip()


def section(title: str, body: str) -> str:
    return f"{RULE}\n{title}\n{RULE}\n\n{body}\n\n"


def wheel_notices(site_packages: pathlib.Path) -> str:
    """Each installed distribution's name, version and licence, from its
    own `.dist-info` METADATA -- plus any licence file it ships."""
    out = []
    for info in sorted(site_packages.glob("*.dist-info")):
        meta_path = info / "METADATA"
        if not meta_path.is_file():
            continue
        meta = email.message_from_string(read(meta_path))
        name = meta.get("Name", info.name)
        version = meta.get("Version", "?")
        licence = meta.get("License-Expression") or meta.get("License") or ""
        classifiers = [c for c in meta.get_all("Classifier", [])
                       if c.startswith("License ::")]
        lines = [f"{name} {version}"]
        if meta.get("Home-page") or meta.get("Project-URL"):
            lines.append("  " + (meta.get("Home-page")
                                 or meta.get_all("Project-URL")[0]))
        if licence.strip() and "\n" not in licence.strip():
            lines.append(f"  Licence: {licence.strip()}")
        for c in classifiers:
            lines.append(f"  {c}")
        texts = sorted(p for p in info.rglob("*")
                       if p.is_file() and p.parent.name == "licenses"
                       or p.name in ("LICENSE", "LICENSE.txt", "LICENSE.md",
                                     "COPYING", "NOTICE"))
        for t in texts:
            lines.append("")
            lines.append(f"  --- {t.relative_to(site_packages)} ---")
            lines += ["  " + ln for ln in read(t).splitlines()]
        out.append("\n".join(lines))
    if not out:
        raise SystemExit("no .dist-info found in %s" % site_packages)
    return "\n\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--archipepsi", type=pathlib.Path, required=True)
    ap.add_argument("--godot-license", type=pathlib.Path, required=True)
    ap.add_argument("--godot-copyright", type=pathlib.Path, required=True)
    ap.add_argument("--python", type=pathlib.Path, required=True)
    ap.add_argument("--site-packages", type=pathlib.Path, required=True)
    ap.add_argument("--mingw", type=pathlib.Path, required=True)
    args = ap.parse_args()

    for p in (args.archipepsi, args.godot_license, args.godot_copyright,
              args.python, args.mingw):
        if not p.is_file():
            raise SystemExit(f"missing: {p}")

    out = [
        "ARCHIPEPSI DIAGNOSTIC BUILD - THIRD-PARTY NOTICES\n",
        "Generated by tools/diagnostic_build/notices.py at build time, from\n"
        "the files it names. Not hand-edited.\n\n",
        section("1. Archipepsi's own assets", read(args.archipepsi)),
        section("2. Godot Engine 4.5.1-stable (MIT) - the game executable\n"
                "   is a Godot export and embeds the engine",
                read(args.godot_license)),
        section("3. Godot Engine - components the engine itself carries\n"
                "   (its COPYRIGHT.txt, verbatim)",
                read(args.godot_copyright)),
        section("4. Python 3.12.10 (PSF licence) - runtime\\python, the\n"
                "   embeddable distribution from python.org",
                read(args.python)),
        section("5. Python libraries bundled with the bridge",
                wheel_notices(args.site_packages)),
        section("6. MinGW-w64 runtime - statically linked into the two\n"
                "   Archipepsi-Diagnostic starter executables",
                "mingw-w64 runtime headers and CRT, ZPL-2.1 and other\n"
                "permissive licences, with GPL-2+ parts not linked here.\n"
                f"Full per-file record as built: {args.mingw}\n"
                "Upstream: https://www.mingw-w64.org/\n"
                "Source: the Debian/Ubuntu mingw-w64 source package."),
    ]
    sys.stdout.write("".join(out).replace("\n", "\r\n"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
