"""Archipepsi v0.5 — binding constants.

SINGLE SOURCE OF TRUTH for every tunable number. Godot reads the same
values from `constants.gd`, generated by `export.py`. Never hand-edit the
GDScript copy.

Two rules govern this file:

1. Every gameplay number in the design lives here. If a spec document
   states a number that is not in this file, this file wins.

2. Derived constants are *derived*, never typed in. The traversal bounds in
   particular are computed from the jump arc, so retuning movement
   recomputes the guarantee instead of silently invalidating it.

Units: metres, seconds, metres/second. Angles in degrees.
"""

from __future__ import annotations

import hashlib
import math
import random

# --------------------------------------------------------------------------
# Campaign shape
# --------------------------------------------------------------------------

LOCATION_COUNT = 30
LOCATION_ID_BASE = 89_100_000
ITEM_ID_BASE = 89_200_000

FIRST_LOCATION_ID = LOCATION_ID_BASE + 1              # 89100001
LAST_LOCATION_ID = LOCATION_ID_BASE + LOCATION_COUNT  # 89100030
GOAL_LOCATION_ID = LAST_LOCATION_ID                   # Check 030

# v0.5 terminology: the soda pun survives only in the project codename.
ITEM_NAME_SIGNAL_KEY = "Signal Key"
ITEM_NAME_EPSILON_COIN = "Epsilon Coin"
ITEM_NAME_EPSILON_STATIC = "Epsilon Static"

ITEM_ID_SIGNAL_KEY = ITEM_ID_BASE + 1                 # 89200001
ITEM_ID_EPSILON_COIN = ITEM_ID_BASE + 2               # 89200002
ITEM_ID_EPSILON_STATIC = ITEM_ID_BASE + 3             # 89200003

SIGNAL_KEY_COUNT = 2
EPSILON_COIN_COUNT = 10
EPSILON_STATIC_COUNT = 18
assert SIGNAL_KEY_COUNT + EPSILON_COIN_COUNT + EPSILON_STATIC_COUNT == LOCATION_COUNT

# --------------------------------------------------------------------------
# Tiers — the mirror APWORLD_SPEC points at (v0.4 referenced an undefined name)
# --------------------------------------------------------------------------

TIER_SIZE = 10
TIER_COUNT = 3

#: Half-open bounds. Tier N holds [TIER_BOUNDS[N], TIER_BOUNDS[N + 1]).
TIER_BOUNDS = tuple(
    FIRST_LOCATION_ID + i * TIER_SIZE for i in range(TIER_COUNT + 1)
)
assert TIER_BOUNDS[-1] == LAST_LOCATION_ID + 1


def tier_of(location_id: int) -> int:
    """Which tier a location belongs to. Tier N requires N Signal Keys."""
    if not FIRST_LOCATION_ID <= location_id <= LAST_LOCATION_ID:
        raise ValueError(f"{location_id} is not an Archipepsi location")
    return (location_id - FIRST_LOCATION_ID) // TIER_SIZE


def locations_in_tier(tier: int) -> list[int]:
    return list(range(TIER_BOUNDS[tier], TIER_BOUNDS[tier + 1]))


def unlocked_location_ids(signal_keys: int) -> list[int]:
    """Every location legal to allocate at this key count, goal included.

    The APWorld region rules and the bridge allocator must both derive from
    this, not re-implement it.
    """
    unlocked = min(signal_keys, TIER_COUNT - 1)
    return list(range(FIRST_LOCATION_ID, TIER_BOUNDS[unlocked + 1]))


# --------------------------------------------------------------------------
# Finale and postgame
# --------------------------------------------------------------------------

FINALE_REQUIRED_SIGNAL_KEYS = 2
FINALE_REQUIRED_OTHER_CHECKS = 24     # of the 29 non-goal Checks

#: v0.5: sending goal does NOT end play. Remaining Checks stay reachable
#: through the Hub until cleared or the player stops. Abandoning real AP
#: locations because the goal fired would strand other players' items.
POSTGAME_ENABLED = True

# --------------------------------------------------------------------------
# Zone allocation
# --------------------------------------------------------------------------

ZONE_TARGET_CHECKS = 3
ZONE_MAX_CHECKS = 3
ZONE_MIN_CHECKS = 2       # 1 only when exactly one eligible Check remains
ZONE_MAX_CHAMBERS = 6
ZONE_MIN_CHAMBERS = 1

# --------------------------------------------------------------------------
# Shop
# --------------------------------------------------------------------------

SHOP_STOCK_SIZE = 2
SHOP_FIRST_STOCK_AFTER_ZONES = 2
SHOP_RESTOCK_EVERY_ZONES = 2
SHOP_PRICE_PROGRESSION = 6
SHOP_PRICE_USEFUL = 4
SHOP_PRICE_OTHER = 2
SHOP_MIN_REMAINING_AFTER_STOCK = ZONE_TARGET_CHECKS

# AP NetworkItem.flags bits
FLAG_PROGRESSION = 0b001
FLAG_USEFUL = 0b010
FLAG_TRAP = 0b100

# --------------------------------------------------------------------------
# Player movement
# --------------------------------------------------------------------------

GRAVITY = 24.0
WALK_SPEED = 7.0
JUMP_VELOCITY = 8.0
COYOTE_TIME = 0.12
JUMP_BUFFER = 0.10
AIR_CONTROL = 0.4

PLAYER_HEIGHT = 1.8
PLAYER_RADIUS = 0.4
PLAYER_EYE_HEIGHT = 1.6

FALL_KILL_Y = -30.0
RESPAWN_DELAY = 1.5

#: An enemy below this counts as dead. Without it, one enemy steered off a
#: tower floor leaves `kill_all` unsatisfiable and the Zone unfinishable.
ENEMY_FALL_KILL_Y = FALL_KILL_Y

# --------------------------------------------------------------------------
# Passive Echo bounds — constrained BY the traversal guarantee
# --------------------------------------------------------------------------
# v0.4 bounded these independently, which let a legal passive Echo make a
# mandatory gap uncrossable: gravity 1.5 dropped jump apex to 0.89 m against
# a 1.0 m mandatory step. The schema forbade positive Echo gates and
# permitted negative ones.
#
# Gravity multipliers may only ever REDUCE gravity, so a gravity Echo is
# always a help. Speed has a floor tight enough that the worst legal
# loadout still clears every mandatory gap.

GRAVITY_MULT_MIN = 0.35
GRAVITY_MULT_MAX = 1.0
SPEED_MULT_MIN = 0.9
SPEED_MULT_MAX = 1.6

# --------------------------------------------------------------------------
# Traversal — derived, and derived for the WORST legal loadout
# --------------------------------------------------------------------------

JUMP_APEX_HEIGHT = JUMP_VELOCITY ** 2 / (2 * GRAVITY)     # 1.333 m
JUMP_AIRTIME = 2 * JUMP_VELOCITY / GRAVITY                # 0.667 s
JUMP_FLAT_REACH = WALK_SPEED * JUMP_AIRTIME               # 4.667 m

#: Margin against imperfect timing, approach angle and air control.
SAFE_GAP_MARGIN = 0.64
SAFE_STEP_MARGIN = 0.75


def _floor1(x: float) -> float:
    """Floor to one decimal. A safety bound must never round upward."""
    return math.floor(x * 10.0) / 10.0


def jump_reach(vertical_step: float = 0.0,
               gravity_mult: float = GRAVITY_MULT_MAX,
               speed_mult: float = SPEED_MULT_MIN) -> float:
    """Horizontal distance covered landing `vertical_step` above takeoff.

    Defaults are the worst legal loadout, so callers get the pessimistic
    answer unless they deliberately ask otherwise.
    """
    g = GRAVITY * gravity_mult
    disc = JUMP_VELOCITY ** 2 - 2 * g * vertical_step
    if disc < 0:
        return 0.0
    return WALK_SPEED * speed_mult * (JUMP_VELOCITY + math.sqrt(disc)) / g


def max_safe_gap(vertical_step: float = 0.0) -> float:
    """Largest gap a mandatory jump may span at this landing height.

    v0.4 bounded gap and step independently, so both could be maxed: the
    real margin was 1.17x, not the 1.56x the flat-jump derivation claimed.
    This is the joint bound.
    """
    return _floor1(jump_reach(vertical_step) * SAFE_GAP_MARGIN)


#: Flat-ground bound. Chambers with a vertical step get a tighter one.
SAFE_BASE_JUMP_GAP = max_safe_gap(0.0)

#: Apex under the worst legal loadout, with margin.
MAX_VERTICAL_STEP = _floor1(
    JUMP_VELOCITY ** 2 / (2 * GRAVITY * GRAVITY_MULT_MAX) * SAFE_STEP_MARGIN
)
MIN_PLATFORM_SIZE = 2.5

# --------------------------------------------------------------------------
# Combat
# --------------------------------------------------------------------------

PLAYER_MAX_HP = 100.0

#: Static Pulse: LMB, always available, never replaced by an equipped Echo.
STATIC_PULSE_DAMAGE = 6.0
STATIC_PULSE_COOLDOWN = 0.35
STATIC_PULSE_RANGE = 40.0
STATIC_PULSE_DPS = STATIC_PULSE_DAMAGE / STATIC_PULSE_COOLDOWN   # ~17.1

ENEMY_STATS = {
    "melee":  {"hp": 24.0,  "damage": 6.0,  "cooldown": 1.0, "speed": 4.0, "reach": 2.0},
    "ranged": {"hp": 16.0,  "damage": 8.0,  "cooldown": 2.0, "speed": 0.0, "reach": 40.0},
    "brute":  {"hp": 120.0, "damage": 18.0, "cooldown": 1.6, "speed": 2.2, "reach": 2.5},
}
ENEMY_AGGRO_RADIUS = 18.0
RANGED_PROJECTILE_SPEED = 14.0

MAX_ENEMIES_PER_ZONE = 14
MAX_ENEMIES_PER_CHAMBER = 8
MAX_BRUTES_PER_ZONE = 1
WORST_CASE_ZONE_TTK_BUDGET = 40.0


def worst_case_zone_ttk() -> float:
    """Seconds of sustained Static Pulse fire to clear the worst legal Zone."""
    brute_hp = ENEMY_STATS["brute"]["hp"] * MAX_BRUTES_PER_ZONE
    grunt_hp = ENEMY_STATS["melee"]["hp"] * (MAX_ENEMIES_PER_ZONE - MAX_BRUTES_PER_ZONE)
    return (brute_hp + grunt_hp) / STATIC_PULSE_DPS


# --------------------------------------------------------------------------
# Echo bounds
# --------------------------------------------------------------------------

ECHO_EFFECTS_MIN = 1
ECHO_EFFECTS_MAX = 3
ECHO_COOLDOWN_MIN = 0.15
ECHO_COOLDOWN_MAX = 15.0

#: Reference mid-bounds Echo, used to state the Static Pulse comparison
#: honestly. The *bounds* permit far more; a typical Echo lands near this.
REFERENCE_ECHO_DAMAGE = 12.0
REFERENCE_ECHO_PELLETS = 3
REFERENCE_ECHO_COOLDOWN = 0.8

# --------------------------------------------------------------------------
# Epsilon
# --------------------------------------------------------------------------

#: Late-90s PC FPS material sets, one per source game. Not voxel palettes:
#: chunky brushwork, grime, harsh lights, industrial fittings.
THEMES = (
    "concrete_facility",   # bright test-chamber facility, clean concrete, vents
    "rusted_industrial",   # oil-drum desert refinery, corrugated steel, scaffold
    "neon_transit",        # underground station, tile, signage, neon spill
    "gothic_stone",        # chunky castle stone, iron, torchlight
    "temple_ruin",         # cracked sandstone, root intrusion, brass fittings
    "void_glitch",         # untextured dev surfaces, missing-texture checker
)
CHAMBER_TYPES = ("corridor", "arena", "platform_path", "tower", "treasure_room")
ENEMY_ARCHETYPES = ("melee", "ranged", "brute")
OBJECTIVES = ("reach_reward", "kill_all", "platform_to_goal")

THEME_BY_GAME_HINT = {
    "Super Mario 64": "concrete_facility",
    "Ocarina of Time": "temple_ruin",
    "Bomb Rush Cyberfunk": "neon_transit",
    "Dark Souls III": "gothic_stone",
    "Borderlands 2": "rusted_industrial",
    "Archipepsi": "void_glitch",
}

#: Procedural texture resolution. v0.4 pinned 16x16 to make life easy for a
#: local model, but Epsilon never paints textures - our code generates them,
#: so the constraint bought nothing and cost the late-90s look.
TEXTURE_SIZE_MIN = 32
TEXTURE_SIZE_MAX = 128
TEXTURE_SIZE_DEFAULT = 64

PROVIDER_TIMEOUT_SECONDS = 60.0
REPAIR_ATTEMPTS = 1

MAX_TEXT_LEN = 160
MAX_DESIGNER_NOTE_LEN = 300
MAX_AP_STRING_LEN = 96

# --------------------------------------------------------------------------
# Epsilon Static
# --------------------------------------------------------------------------

STATIC_GLITCH_UNITS_PER_ITEM = 1
STATIC_GLITCH_VISUAL_CAP = 18


# --------------------------------------------------------------------------
# Determinism
# --------------------------------------------------------------------------

def prng_seed(*parts: object) -> int:
    """Stable 64-bit seed from a campaign key.

    Never use Python's built-in hash(): it is randomized per process.
    """
    key = "|".join(str(p) for p in parts)
    return int.from_bytes(hashlib.sha256(key.encode("utf-8")).digest()[:8], "big")


def deterministic_shuffle(items: list, *seed_parts: object) -> list:
    """Fisher-Yates over a seeded Mersenne Twister. Returns a new list.

    Descending index, j = rng.randrange(i + 1). Any reimplementation must
    match exactly, including loop direction. Pinned by test.
    """
    rng = random.Random(prng_seed(*seed_parts))
    out = list(items)
    for i in range(len(out) - 1, 0, -1):
        j = rng.randrange(i + 1)
        out[i], out[j] = out[j], out[i]
    return out


def track_order_seed(seed_name: str, team: int, slot_id: int) -> tuple:
    return (seed_name, team, slot_id, "track_order")


def zone_selection_seed(seed_name: str, team: int, slot_id: int,
                        generation_counter: int, target_game: str) -> tuple:
    """Same tuple shape as track_order_seed plus the per-Zone discriminators.

    v0.4 dropped `team` here, so two slots on different teams with the same
    slot_id got identical Zone shuffles.
    """
    return (seed_name, team, slot_id, generation_counter, target_game)
