"""MENU-INT — the Glyph interface kit the game draws is the art lane's.

`assets/ui` is the art lane's output (Arty's Glyph kit, regenerated by
`tools/glyphui/*` and measured by `tools/content/run_font_import.sh` and
`run_ui_icons.sh`). `tools/import_ui_kit.sh` ships it to
`godot/content/ui`, byte for byte, where the menu reads it. These checks
fail when the two drift apart -- a font whose metrics the verifiers never
saw, or a symbol the game draws and the art lane no longer has -- and when
the engine's sidecars would let Godot recompress the pixel art.

**Nothing here regenerates an asset.** A failure is fixed by running
`tools/import_ui_kit.sh`, never by editing either copy.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "assets/ui"
SHIPPED = ROOT / "godot/content/ui"


def _files(directory: Path) -> dict[str, bytes]:
    return {f.name: f.read_bytes() for f in sorted(directory.iterdir())
            if f.is_file() and not f.name.endswith(".import")}


def test_the_game_ships_exactly_the_art_lanes_kit():
    source = _files(SOURCE)
    shipped = _files(SHIPPED)
    assert source, "no Glyph kit in assets/ui"
    assert sorted(shipped) == sorted(source), (
        "godot/content/ui and assets/ui name different files: run "
        "tools/import_ui_kit.sh")
    differ = [name for name in source if shipped[name] != source[name]]
    assert not differ, f"not byte-identical to assets/ui: {differ}"


def test_every_symbol_the_contract_names_is_shipped():
    icons = json.loads((SHIPPED / "icons.json").read_text(encoding="utf-8"))
    for key, entry in icons.items():
        if key.startswith("_"):
            continue
        assert (SHIPPED / entry["file"]).is_file(), (key, entry["file"])
        # Every symbol has a readable fallback for a text-only prompt.
        assert str(entry.get("text", "")).strip(), key


def test_the_engine_imports_the_pixels_losslessly():
    pngs = sorted(SHIPPED.glob("*.png"))
    assert pngs
    for png in pngs:
        sidecar = png.with_name(png.name + ".import")
        assert sidecar.is_file(), f"{png.name} was never imported"
        text = sidecar.read_text(encoding="utf-8")
        params = dict(re.findall(r"^([\w/]+)=(.*)$", text, flags=re.M))
        assert params.get("compress/mode") == "0", (png.name, "lossless")
        assert params.get("mipmaps/generate") == "false", png.name
        # Used on 3D walls: a texture Godot sees in 3D is otherwise
        # recompressed into a lossy VRAM format on the next import.
        assert params.get("detect_3d/compress_to") == "0", png.name


def test_the_faces_import_as_bitmap_fonts_at_whole_pixel_scales():
    for face in ("ui_text", "ui_numerals"):
        sidecar = SHIPPED / f"{face}.fnt.import"
        assert sidecar.is_file(), face
        text = sidecar.read_text(encoding="utf-8")
        assert 'importer="font_data_bmfont"' in text, face
        # FIXED_SIZE_SCALE_ENABLED: what the font-import verifier measured
        # ("scale mode: imported 2").
        assert re.search(r"^scaling_mode=2$", text, flags=re.M), face
