#!/usr/bin/env python3
"""Optional check: does the committed Glyph interface kit still come from
the Glyph revision it is recorded against?

    python3 tools/check_ui_kit_provenance.py
    GLYPH_ROOT=<built ECMS Glyph checkout> python3 tools/check_ui_kit_provenance.py

## Why this exists

`assets/ui` (two bitmap fonts, 30 symbols, 4 nine-slice panels and their
JSON, 40 files) is generated by the art lane's `tools/glyphui/author_*.py`
from a Glyph checkout named by `GLYPH_ROOT`. Nothing recorded WHICH Glyph
built it, and `tools/check_art_current.sh` does not cover `assets/ui`, so a
Glyph upgrade could change the kit, or the next person could fail to
reproduce it, without anything saying so. The 2026-10-08 pipeline audit
rebuilt the kit by hand from ECMS-GLYPH `2e2115a` and got 40 of 40 files
byte-identical; this is that loop, kept.

## What it does

1. Always: every file in `assets/ui` matches the sha256 recorded in
   `tools/ui_kit_provenance.json`, and no file is missing or extra. A
   failure here means the kit changed and the record did not.
2. Only when `GLYPH_ROOT` is set: runs the four authoring scripts into a
   temporary directory and compares every output byte for byte against
   the committed kit. If the checkout is not at the recorded revision it
   says so, and the comparison then answers "does THIS Glyph still build
   the same kit?" -- the question an upgrade needs answered.

Without `GLYPH_ROOT`, step 2 is skipped and reported as SKIP, not PASS.

## What it never does

It never writes to `assets/ui` or `godot/content/ui`, and it opens no
existing `.glyph` file: the authoring scripts create fresh projects in
their own temp directories. Regenerated files live in a temp directory
that is deleted afterwards (`--keep` leaves it, for diffing).

`--write-record` rewrites `tools/ui_kit_provenance.json` from the kit as
committed now. It is for whoever changes the kit, after they have changed
it on purpose; it still never touches the kit itself.

Exit status: 0 pass (or pass with the rebuild skipped), 1 mismatch,
2 could not run.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RECORD = ROOT / "tools" / "ui_kit_provenance.json"
KIT = ROOT / "assets" / "ui"
#: Each script writes its share of the kit into the directory it is given.
AUTHORS = ("author_numerals.py", "author_text.py",
           "author_icons.py", "author_panels.py")


def say(msg: str) -> None:
    print("check-ui-kit: %s" % msg)


def kit_files(directory: Path) -> dict[str, str]:
    """name -> sha256 of every regular file directly in `directory`."""
    return {f.name: hashlib.sha256(f.read_bytes()).hexdigest()
            for f in sorted(directory.iterdir()) if f.is_file()}


def compare(expected: dict[str, str], actual: dict[str, str],
            label: str) -> list[str]:
    faults = []
    for name in sorted(set(expected) - set(actual)):
        faults.append("%s: %s is missing" % (label, name))
    for name in sorted(set(actual) - set(expected)):
        faults.append("%s: %s is not in the record" % (label, name))
    for name in sorted(set(expected) & set(actual)):
        if expected[name] != actual[name]:
            faults.append("%s: %s differs" % (label, name))
    return faults


def glyph_revision(checkout: Path) -> str | None:
    out = subprocess.run(["git", "-C", str(checkout), "rev-parse", "HEAD"],
                         capture_output=True, text=True)
    return out.stdout.strip() if out.returncode == 0 else None


def regenerate(checkout: Path, out_dir: Path) -> None:
    env = dict(os.environ, GLYPH_ROOT=str(checkout))
    env.pop("GLYPH_KEEP_WORK", None)
    for script in AUTHORS:
        path = ROOT / "tools" / "glyphui" / script
        proc = subprocess.run([sys.executable, str(path), str(out_dir)],
                              env=env, capture_output=True, text=True)
        if proc.returncode != 0:
            raise RuntimeError("%s failed:\n%s\n%s" % (
                script, proc.stdout[-2000:], proc.stderr[-2000:]))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--kit", type=Path, default=KIT,
                    help="kit directory to check (default assets/ui)")
    ap.add_argument("--record", type=Path, default=RECORD,
                    help="provenance record (default "
                         "tools/ui_kit_provenance.json)")
    ap.add_argument("--keep", action="store_true",
                    help="keep the regenerated kit and print its path")
    ap.add_argument("--write-record", action="store_true",
                    help="rewrite the record's file hashes from the kit "
                         "as it is now; the kit itself is never touched")
    args = ap.parse_args(argv)

    if not args.kit.is_dir():
        say("no kit at %s" % args.kit)
        return 2
    try:
        record = json.loads(args.record.read_text())
    except (OSError, ValueError) as exc:
        say("cannot read record %s: %s" % (args.record, exc))
        return 2
    committed = kit_files(args.kit)

    if args.write_record:
        record["files"] = committed
        args.record.write_text(json.dumps(record, indent=2) + "\n")
        say("record rewritten: %d file(s). Update glyph.revision too if "
            "the kit was rebuilt from a different Glyph." % len(committed))
        return 0

    status = 0
    recorded_rev = record["glyph"]["revision"]
    say("recorded Glyph revision %s (%s)"
        % (recorded_rev[:7], record["glyph"]["repository"]))

    # --- 1. the committed kit is the recorded kit ----------------------
    faults = compare(record["files"], committed, "record")
    if faults:
        status = 1
        for f in faults:
            say("FAIL -- " + f)
        say("the kit changed and the record did not. If the change was "
            "deliberate, rebuild with the matching Glyph and run "
            "--write-record.")
    else:
        say("record: %d of %d file(s) match" % (len(committed),
                                                len(record["files"])))

    # --- 2. Glyph rebuilds the committed kit ----------------------------
    checkout = os.environ.get("GLYPH_ROOT")
    if not checkout:
        say("SKIP rebuild -- set GLYPH_ROOT to a built ECMS Glyph checkout "
            "(revision %s) to regenerate and compare" % recorded_rev[:7])
        return status
    checkout_path = Path(checkout).resolve()
    if not (checkout_path / "packages" / "cli" / "dist" / "main.js").exists():
        say("no built Glyph CLI under %s (npm ci && npx tsc -b there)"
            % checkout_path)
        return 2
    rev = glyph_revision(checkout_path)
    if rev is None:
        say("NOTE -- %s is not a git checkout; its revision is unknown"
            % checkout_path)
    elif rev != recorded_rev:
        say("NOTE -- GLYPH_ROOT is at %s, not the recorded %s; the rebuild "
            "below tests whether THIS Glyph reproduces the kit"
            % (rev[:7], recorded_rev[:7]))
    else:
        say("GLYPH_ROOT is at the recorded revision")

    out_dir = Path(tempfile.mkdtemp(prefix="ui_kit_rebuild_"))
    try:
        say("rebuilding into %s ..." % out_dir)
        try:
            regenerate(checkout_path, out_dir)
        except RuntimeError as exc:
            say("FAIL -- rebuild did not complete: %s" % exc)
            return 2
        rebuilt = kit_files(out_dir)
        faults = compare(committed, rebuilt, "rebuild")
        if faults:
            status = 1
            for f in faults:
                say("FAIL -- " + f)
        else:
            say("rebuild: %d of %d file(s) byte-identical"
                % (len(rebuilt), len(committed)))
    finally:
        if args.keep:
            say("kept %s" % out_dir)
        else:
            shutil.rmtree(out_dir, ignore_errors=True)

    say("PASS" if status == 0 else "FAIL")
    return status


if __name__ == "__main__":
    sys.exit(main())
