#!/usr/bin/env bash
# Ship the Glyph interface kit (assets/ui, the art lane's output) to the
# game, byte for byte, and run Godot's OWN importer over it.
#
#   tools/import_ui_kit.sh
#
# THE SOURCE IS assets/ui. It is generated by the art lane's tools
# (`tools/glyphui/author_text.py`, `author_icons.py`) and verified by
# `tools/content/run_font_import.sh` and `run_ui_icons.sh`. This copies it
# to `godot/content/ui/`, the destination the theme pack set a precedent
# for (`godot/content/theme/`), and rewrites nothing: the menu reads the
# same bytes the art lane's verifiers measured. A file that leaves
# assets/ui leaves the game too. `bridge/tests/test_ui_kit_identity.py`
# fails if the two ever differ.
#
# THE SIDECARS ARE THE ENGINE'S (see tools/import_godot_content.sh for why
# a hand-written .import is a guess). One parameter is set afterwards, in
# the [params] block the editor writes to: `detect_3d/compress_to=0`. The
# kit is pixel art drawn on the menu's 3D walls, and Godot's default
# recompresses a texture it sees used in 3D into lossy VRAM formats on the
# next import -- a glyph's one-pixel strokes would smear. Mipmaps stay off
# (the default): the faces are drawn with a nearest filter at whole-pixel
# scales. Then the importer runs again, so everything derived stays Godot's.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GODOT="${GODOT:-$ROOT/.tools/godot}"
[ -x "$GODOT" ] || { echo "no godot at $GODOT" >&2; exit 2; }
SRC="$ROOT/assets/ui"
DEST="$ROOT/godot/content/ui"
[ -f "$SRC/ui_text.fnt" ] || { echo "no Glyph kit in $SRC" >&2; exit 2; }

mkdir -p "$DEST"
# Files the kit no longer has go, with their sidecars.
for f in "$DEST"/*; do
  [ -e "$f" ] || continue
  base="$(basename "$f")"
  case "$base" in *.import) continue ;; esac
  [ -f "$SRC/$base" ] || rm -f "$f" "$f.import"
done
for f in "$SRC"/*; do
  cp "$f" "$DEST/"
done

run_import() {
  local log
  log="$(mktemp)"
  set +e
  xvfb-run -a timeout --kill-after=15s "${GODOT_IMPORT_TIMEOUT:-600}" \
    "$GODOT" --headless --path "$ROOT/godot" --import >"$log" 2>&1
  local status=$?
  set -e
  grep -E "SCRIPT ERROR|USER ERROR|Failed to load" "$log" | head -5 || true
  if [ "$status" -ne 0 ]; then
    echo "import_ui_kit: the engine exited $status; full log at $log" >&2
    exit 1
  fi
  rm -f "$log"
}

run_import
python3 - "$DEST" <<'EOF'
import pathlib, re, sys
dest = pathlib.Path(sys.argv[1])
changed = 0
for f in sorted(dest.glob("*.png.import")):
    text = f.read_text()
    fixed = re.sub(r"^detect_3d/compress_to=\d+$", "detect_3d/compress_to=0",
                   text, flags=re.M)
    if fixed != text:
        f.write_text(fixed)
        changed += 1
print("import_ui_kit: 3D recompression turned off in %d sidecar(s)" % changed)
EOF
run_import
echo "import_ui_kit: $(ls "$SRC" | wc -l) file(s) shipped to godot/content/ui"
