"""The two hall figures the owner's verdict changed, and only those two.

    python3 tools/shots/gen_hall_verdict.py
    tools/shoot.sh tools/shots/hall_verdict.json docs/art/review/hall_owner_verdict

WHY TWO AND NOT FOURTEEN. The owner's two changes -- three grapple
offers and one traversal segment closing the collar -- are DECLARATIONS.
An offer reserves a place and a traversal segment describes a way
through; neither models anything. `shell_hall_transit.glb` came out of
the build byte-identical, so every view of the room is the same picture
it was, and re-rendering sixteen unchanged images to sit beside two
changed ones would just make it harder to see which two moved.

The figures that DO change are the two derived from the parts of the
manifest that moved:

    O2_route      gains the optional segment that closes the collar
    O5_overhead   gains the three anchors, on the rings it already drew

`docs/art/review/hall_67add07/` keeps the versions the owner actually
reviewed. This directory is what the room declares now.

The cameras are lifted verbatim from `p3_owner_review.json` rather than
re-derived, so the new figures can be held against the old ones without
a camera move confusing the comparison.
"""

import json
import pathlib

SOURCE = pathlib.Path("tools/shots/p3_owner_review.json")
WANTED = ("O2_route", "O5_overhead")

main = json.loads(SOURCE.read_text())
shots = [s for s in main["shots"] if s["name"] in WANTED]
missing = set(WANTED) - {s["name"] for s in shots}
if missing:
    raise SystemExit("p3_owner_review.json no longer has %s -- regenerate it "
                     "with gen_p3_owner_review.py first" % sorted(missing))

main["_comment"] = [
    "HALL OWNER VERDICT -- the two figures the verdict changed.",
    "GENERATED by tools/shots/gen_hall_verdict.py; edit that.",
    "",
    "Owner verdict on the library review: HALL FORM PASS WITH TWO",
    "CHANGES. Three grapple_point offers on the collar rings, and one",
    "traversal segment closing the collar walk from a C into a loop.",
    "",
    "Both are declarations. No geometry was added or moved, and the",
    "shell exported byte-identical -- so these are the only two of the",
    "package's eighteen images that are different.",
    "",
    "The shell still exports review: 'pending' until Production",
    "recertifies the changed contract.",
]
main["shots"] = shots

out = pathlib.Path("tools/shots/hall_verdict.json")
out.write_text(json.dumps(main, indent=2) + "\n")
print("wrote", out, "with", len(shots), "shots")
