"""Wave 1 owner-review shot lists, one generator for three rooms.

    python3 tools/shots/gen_wave1_review.py
    tools/shoot.sh tools/shots/wave1_review.json docs/art/review/wave1

ONE GENERATOR, because ten rooms authored ten review packages by hand is
ten packages that drift. Cameras are computed by `aim()` from anchors
read out of each room's SHIPPED manifest, so a camera cannot end up
pointing somewhere the room no longer is.

Render space (L-52): a Godot manifest point with x and z negated; a rig
yaw of theta looks along `(sin theta, 0, cos theta)`; `eye` adds an eye
height that `look` does not.
"""

import json
import math
import pathlib

EYE = 1.6
MANIFEST = pathlib.Path("assets/models/batch040/shells/manifest.json")
M = json.loads(MANIFEST.read_text())


def R(x, y, z):
    return [round(-x, 3) + 0.0, round(y, 3) + 0.0, round(-z, 3) + 0.0]


def aim(eye_r, at_r, lift=EYE):
    dx, dz = at_r[0] - eye_r[0], at_r[2] - eye_r[2]
    dy = at_r[1] - (eye_r[1] + lift)
    flat = math.hypot(dx, dz)
    return (round(math.degrees(math.atan2(dx, dz)) % 360.0, 1),
            round(math.degrees(math.atan2(dy, flat)) if flat > 1e-6 else 0.0, 1))


shots = []


def view(cid, tag, eye_r, at_r, caption, note, light, size=(1920, 1080)):
    yaw, pitch = aim(eye_r, at_r)
    shots.append(dict(light, name="%s_%s" % (tag, cid.split("_", 1)[1]),
                      scene="model:batch040/shells/%s.glb" % cid,
                      size=list(size), eye=eye_r, yaw=yaw, pitch=pitch,
                      caption=caption, note=note))


# A tall shaft, a wide field and a long span want different keys: the
# plenum is lit for depth down a hole, the yard for a flat floor read.
SHAFT = {"ambient": 0.34, "key_energy": 1.20}
FIELD = {"ambient": 0.30, "key_energy": 1.15}

# ------------------------------------------------------- plenum (shaft)
P = "shell_plenum_helix"
view(P, "A1", R(0.0, 68.0, 3.0), R(0.0, 20.0, 12.0),
     "PLENUM - ENTRY, AT THE TOP, LOOKING DOWN",
     "THE FIRST DECISION IS MADE HERE: THE FLOOR IS 68 M BELOW", SHAFT)
view(P, "A2", R(0.0, 2.0, 3.0), R(0.0, 66.0, 11.0),
     "PLENUM - FROM THE FLOOR, THE FULL 72 M",
     "THE MACHINE HANGS AND NEVER LANDS. THE FLOOR IS WHOLE", SHAFT)
view(P, "A3", R(-7.5, 40.0, 4.0), R(2.0, 26.0, 14.0),
     "PLENUM - MID SHAFT, ON THE HELIX",
     "TWELVE RUNS, THREE TURNS. THE MACHINE HIDES THE FAR WALL", SHAFT)
view(P, "A4", R(6.0, 30.0, 4.0), R(-2.0, 29.0, 12.0),
     "PLENUM - A COLLAR, THE ONLY ROOM THAT IS NOT THE WALL",
     "THREE OF THESE. REACHED BY A BRIDGE, OR BY RAIL, OR NOT AT ALL", SHAFT)

# -------------------------------------------------------- yard (field)
Y = "shell_yard_gantry"
view(Y, "B1", R(-38.0, 0.0, 26.0), R(30.0, 6.0, 26.0),
     "YARD - ENTRY, ACROSS 84 M OF FLOOR",
     "THE CRANE TELLS YOU HOW WIDE THE ROOM IS BEFORE YOU CROSS IT", FIELD)
view(Y, "B2", R(-30.0, 13.5, 8.0), R(20.0, 2.0, 40.0),
     "YARD - FROM THE CRANE BRIDGE, THE WHOLE FLOOR",
     "COVER CLUSTERS, TWO DOCKS, AND A CATWALK RING AT 8 M", FIELD)
view(Y, "B3", R(-40.0, 8.0, 4.0), R(30.0, 8.0, 40.0),
     "YARD - ALONG THE CATWALK AT 8 M",
     "AN OPTIONAL HEIGHT. THE MANDATORY ROUTE NEVER LEAVES THE FLOOR", FIELD)
view(Y, "B4", R(20.0, 1.5, 40.0), R(-20.0, 10.0, 14.0),
     "YARD - IN COVER, LOOKING BACK ACROSS",
     "WHAT A RANGED ENEMY ON THE CATWALK CAN SEE, AND WHAT IT CANNOT", FIELD)

# -------------------------------------------------------- span (bridge)
S = "shell_span_basin"
view(S, "C1", R(0.0, 14.0, 4.0), R(0.0, 12.0, 86.0),
     "SPAN - ENTRY, ON THE DECK, 90 M OF IT",
     "NO RAILING. THE FALL IS THE OTHER ROUTE, NOT A RELOAD", FIELD)
view(S, "C2", R(0.0, 0.0, 6.0), R(0.0, 13.0, 60.0),
     "SPAN - FROM THE BASIN, UNDER THE DECK",
     "A COMPLETE SECOND ROUTE. COVERED, SLOWER, AND BLIND AT THE FAR END",
     FIELD)
view(S, "C3", R(-11.0, 18.0, 12.0), R(2.0, 8.0, 55.0),
     "SPAN - THE TWO ROUTES AT ONCE",
     "PYLONS AT 0.3 AND 0.7 OF THE LENGTH, WITH A PERCH ON EACH", FIELD)
view(S, "C4", R(9.0, 2.0, 62.0), R(-2.0, 13.0, 30.0),
     "SPAN - BASIN FLOOR, LOOKING BACK UP AT THE SPAN",
     "THE RAIL IS SLUNG UNDER THE DECK, AT A THIRD HEIGHT", FIELD)

out = pathlib.Path("tools/shots/wave1_review.json")
out.write_text(json.dumps({
    "_comment": [
        "WAVE 1 OWNER REVIEW -- three LARGE shells, all review: pending.",
        "GENERATED by tools/shots/gen_wave1_review.py; edit that.",
        "Four views each: entry read, the landmark, the topology, and the",
        "local space that is most easily missed. Cameras are computed",
        "from manifest anchors rather than eyeballed.",
    ],
    "defaults": {"size": [1920, 1080], "backdrop": "none", "game_lens": True},
    "shots": shots,
}, indent=2) + "\n")
print("wrote", out, "with", len(shots), "shots")
